### ISSUE TITLE
ZED reopening problem

### ISSUE THREAD

**Issue by pavloblindnology** [stereolabs/zed-examples#10]
Hi,
I'm using ZED camera and need to reopen it during program execution (to change resolution, etc.).
The problem is that the GPU memory allocated after ZED camera opened becomes invalid after ZED closed.
So, for example, the next code will cause an OpenCV error
"OpenCV Error: Gpu API call (invalid argument) in cv::cuda::GpuMat::download, file C:/opencv/sources/modules/core/src/cuda/gpu_mat.cu, line 249"

    sl::Camera zed;
    zed.open(...);
    cv::cuda::GpuMat gmat(...);
    zed.close();

    cv::cuda::GpuMat gmat1;
    gmat.copyTo(gmat1);
    or
    cv::Mat mat;
    gmat.download(mat);

As I understand this is because ZED creates its own CUDA context, which becomes invalid after reopening.
One workaround is to release all cv::cuda::GpuMats after closing ZED camera, but it's veeery inconvenient, since the program can have tons of them spread all over the program.
Is there an easier way? 
What is the need for ZED to create its own CUDA context?

**Comment by nesnes** [comment]
Hi,

After calling the close method, the CUDA context is destroyed.
Your solution to keep the images will be to copy the Mat on the CPU before the close().
Here is a sample code:

```
sl::Mat mat_keep_cpu;
{
    sl::Camera zed_;
    zed_.open();
    sl::Mat imageDisplay;
    zed_.grab();
    zed_.retrieveImage(imageDisplay, sl::VIEW_LEFT, sl::MEM_GPU);

    imageDisplay.copyTo(mat_keep_cpu, sl::COPY_TYPE_GPU_CPU);
    imageDisplay.free();
    zed_.close();
}

{
    sl::Camera zed_;
    sl::Mat imageDisplay_new;
    zed_.open();
    imageDisplay_new.setFrom(mat_keep_cpu, sl::COPY_TYPE_CPU_GPU);
}
std::cout << "Done" << std::endl;
exit(0);
```
