### ISSUE TITLE
Where can i get the source code of ZEDfu app？

### ISSUE THREAD

**Issue by WongRZ** [stereolabs/zed-examples#101]
Dear author,
The zed-examples don't contain the source code of ZEDfu app, how can i get it?
Thank you.

**Comment by rnunziata** [comment]
zedfu seems to some kind of variation of pcl_kinfu...for which there is source. I  would also like to get the zedfu version.

**Comment by obraun-sl** [comment]
A basic version of ZEDfu (same functions) is the spatial mapping example. It does call the exact same function of ZEDfu.
