### ISSUE TITLE
ZED SVO export erreo

### ISSUE THREAD

**Issue by Zhefei777** [stereolabs/zed-examples#103]
I am trying to run the example SVO recording export. but I got this error. 

**build$ make
[ 50%] Building CXX object CMakeFiles/ZED_SVO_Export.dir/src/main.o
/home/zhefei/Desktop/zed-examples-master/svo recording/export/src/main.cpp: In function ‘int main(int, char**)’:
/home/zhefei/Desktop/zed-examples-master/svo recording/export/src/main.cpp:133:50: error: ‘CV_FOURCC’ was not declared in this scope
         int fourcc = CV_FOURCC('M', '4', 'S', '2'); // MPEG-4 part 2 codec
                                                  ^
/home/zhefei/Desktop/zed-examples-master/svo recording/export/src/main.cpp:183:69: error: ‘CV_RGBA2RGB’ was not declared in this scope
                 cv::cvtColor(svo_image_sbs_rgba, ocv_image_sbs_rgb, CV_RGBA2RGB
                                                                     ^
CMakeFiles/ZED_SVO_Export.dir/build.make:62: recipe for target 'CMakeFiles/ZED_SVO_Export.dir/src/main.o' failed
make[2]: *** [CMakeFiles/ZED_SVO_Export.dir/src/main.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/ZED_SVO_Export.dir/all' failed
make[1]: *** [CMakeFiles/ZED_SVO_Export.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2**

Is there a fix for it?

**Comment by gopikrishnan99** [comment]
Hey. Even i came across this exact error. I was wondering what fix have you found for the it?
