### ISSUE TITLE
ZEDFu spatial mapping with svo file

### ISSUE THREAD

**Issue by specyfick** [stereolabs/zed-examples#104]
Hi, 
I have recorded svo file with the application SVO Recording form sample.
Loading SVO file to the Zed fu does not gives me a spatial mapping.
Does it required some special settings for recording svo file and the go to spatial mapping from it ?

**Comment by bill97385** [comment]
Same Here~~ Is there any idea?

**Comment by KevinGriffin31** [comment]
Also having this issue with an error that the SVO file doesn't have enough matrixes.

**Comment by BingXiong1995** [comment]
Same Here! after two years the problem is still here
