### ISSUE TITLE
Jetson Xavier doesn't work

### ISSUE THREAD

**Issue by jwatte** [stereolabs/zed-examples#108]
I'm trying to use a Zed camera with the Jetson Xavier, but it doesn't work, because the current Jetson SDK is cuda 9.2, and the Xavier uses cuda 10.0. Also, the TX2 uses Ubuntu 16.04, but Xavier uses Ubuntu 18.04, updating some shared library versions.

Given that the Xavier has extra hardware for stereo disparity acceleration, it would be great to see that used, but even without that hardware, I currently just have a very expensive webcam with double vision.

**Comment by WASCHMASCHINE** [comment]
Why did you buy it in the first place then?
SDK 2.7 will feature CUDA 10 and will be released this week, since it was already in testing last week. Hopefully.

**Comment by Myzhar** [comment]
@jwatte, the SDK for the Xavier is coming soon. There were a few issues to be solved with the new Nvidia hardware and with the new CUDA version, but after completing the testing phase we are going to release it.
You must understand that the Xavier introduced a lot of novelties, both hardware and software, and a bit of time is required to verify that everything work as expected, but now it is a matter of a few days.

**Comment by jwatte** [comment]
Thank you for the update @Myzhar ! Looking forward to it.

**Comment by Myzhar** [comment]
Here you are
https://www.stereolabs.com/developers/release/2.7/

**Comment by jwatte** [comment]
Great! Quick fix for the issue :-)

**Comment by kdhakal18** [comment]
> Great! Quick fix for the issue :-)

How did you fix this? The SDK seems to get installed but doesn't work perfectly.

**Comment by Myzhar** [comment]
@kdhakal18 what kind of problems are you getting?
Please open a new issue providing more details so we can help you
