### ISSUE TITLE
Tensorflow and YOLO examples in SDK v2.7

### ISSUE THREAD

**Issue by pvishal-carnd** [stereolabs/zed-examples#110]
I just updated to the newly released SDK v2.7 and the release notes mention introducing Tensorflow and YOLO examples. I couldn't find them in the samples that install with the SDK or in this repo. Where should I be looking?

Thanks!

**Comment by adujardin** [comment]
The [release notes](https://www.stereolabs.com/developers/release/2.7/) have been updated with the links to each Github repositories ([TF](https://github.com/stereolabs/zed-tensorflow), [YOLO](https://github.com/stereolabs/zed-yolo)).
