### ISSUE TITLE
Retrieve point cloud for each frame in real-time

### ISSUE THREAD

**Issue by morimkb** [stereolabs/zed-examples#124]
Hi, 
I have retrieved the point cloud of each frame from a video easily by using open cv and saveDepth example available in ZED library, but now I need to make it work in real-time.
I have noticed that in the sample you are using savePointCloudAs() function to save the point cloud, but I need to save them all in a Mat in real-time and use them in projectPoint() in openCV..
You provided a function point_cloud.getValue(x,y, &point_cloud_value) which returns only a single point from point clouds. what if I want access all the point clouds in each frame? 
Thank you.

**Comment by wulaladamowang** [comment]
use float* data_points = point_cloud.getPtr<float>()    api"getPtr" may be useful.
