### ISSUE TITLE
CMake failed the configuration 

### ISSUE THREAD

**Issue by ZHOUXIAOYI95** [stereolabs/zed-examples#125]
Hi, I'm a beginner. I followed each step of the tutorial instruction, but the Cmake cannot configure the project file and the warning shows ' error in the configuration process, project file may be invalid'. 

Please offer me any ideal to solve it. Many thanks!
![annotation 2019-02-11 000910](https://user-images.githubusercontent.com/46758172/52541870-c3ccd680-2d91-11e9-9b04-65b08a3868e0.jpg)

**Comment by obraun-sl** [comment]
Hi,
You need to install visual studio 2015 or 2017 (C++) to be able to build examples. 
OB

**Comment by ZHOUXIAOYI95** [comment]
> Hi,
> You need to install visual studio 2015 or 2017 (C++) to be able to build examples.
> OB

hi, problem solved, many thanks.
