### ISSUE TITLE
binary release of svo export utiltity?

### ISSUE THREAD

**Issue by eric-schleicher** [stereolabs/zed-examples#128]
I don't see a binary of the SVO export anywhere.  I'm not quite ninja enough to compile.  is there a us/supported way to do this without setting up a development environment?

**Comment by obraun-sl** [comment]
Hi,
The binaries are only given with the ZED SDK installer on Windows in samples/bin/
We don't provide them on github, only source code.

Best,
OB

**Comment by eric-schleicher** [comment]
Thank you!  This is exactly what i was looking for.

![image](https://user-images.githubusercontent.com/8261783/53105198-85e45680-34e5-11e9-9c83-7b31a6cc3e43.png)
