### ISSUE TITLE
Zed SDK 2.7.1 cuda 10.1 and ubuntu 16

### ISSUE THREAD

**Issue by pamarinp** [stereolabs/zed-examples#130]
I have tried the install file version ZED_SDK_Linux_Ubuntu16_v2.3.3.run located in the ZED usb and they said I have cuda version 10.1 but it works only with 9.0, therefore it will not work with cuda.

I download the last version ZED_SDK_Linux_Ubuntu16_v2.7.1.run and they said again I have installed cuda 10.1 but it required cuda 10.0 and zed will not work with cuda.

Do you know any install file that works with cuda 10.1 and ubuntu 16.04?

**Comment by Hubert51** [comment]
Same question. It seems the zed does not work with cuda 10.1. Do you find some solutions?

**Comment by jagin** [comment]
+1

**Comment by agirgen** [comment]
+1, especially since the download link on the SDK page takes you to the 10.1 download.  And the Nvidia download page says its version 10, not version 10.1.  Time wasted.

**Comment by snakehaihai** [comment]
+1. ZED need Cuda 10. So I choose Cuda 10 on nvidia download section. but nvidia gives me 10.1. So any hot fixs?

**Comment by matlabbe** [comment]
Download 10.0 archive here: https://developer.nvidia.com/cuda-10.0-download-archive
