### ISSUE TITLE
Repair the depth image by the RGBA image

### ISSUE THREAD

**Issue by hanchengzhe** [stereolabs/zed-examples#135]
![111](https://user-images.githubusercontent.com/48611171/54470529-37746000-47e4-11e9-8d5f-9e7678201a7a.png)
Hi, I am working on the depth image returned by ZED. I found the depth information of some points is not accurate(such as the area around my finger), how can this be fixed by the RGBA image or normal image using color and texture features?

**Comment by WASCHMASCHINE** [comment]
You could turn off the fill option, which is more accurate but less dense with holes. You could then try to separate background and foreground pixels via color alone if your goal is hand-tracking. Then you could interpolate the background depth around the hand contours.

Alternatively do your own stereo by training a CNN on many similar images like this with ground truth.

**Comment by GiuseppeLozioEllena** [comment]
Hi, I have a similar problem with Unity Zed plugin. It's possible to increase the precision of occlusion on holes. I want to avoid this :
![picture2](https://user-images.githubusercontent.com/9770088/60101993-1b764800-975d-11e9-93c0-0299a8ed0618.png)
