### ISSUE TITLE
LIVE Map and Point Cloud Data till the current instance.

### ISSUE THREAD

**Issue by nalinraut** [stereolabs/zed-examples#140]
1.  I am aware that we can retrieve point clouds from each frame, however, I want the entire point cloud until the current frame with respect to the initial frame. Is that possible using ZED SDK without applying the transformations?  I need just the point cloud til the current instance in order to perform further operations. 

2. In addition to this, is there a way to obtain a map till the current instance without using ZEDfu?

**Comment by P-yver** [comment]
Hi,
you can use the spatial mapping API from [this sample](https://github.com/stereolabs/zed-examples/tree/master/spatial%20mapping/advanced%20point%20cloud%20mapping)

Or, you can retrieve all point clouds from retrieveMeasure with `sl::RuntimeParameters::REFERENCE_FRAME = REFERENCE_FRAME ::WORLD` after enabling the positional tracking.
All point clouds will be expressed in world coordinate so you can see the entire space (but you will have overlap between them)
