### ISSUE TITLE
Zed not working after firmware crash

### ISSUE THREAD

**Issue by WYZong** [stereolabs/zed-examples#144]
I have some problem on the ZED firmware. 
I was trying to update my ZED firmware version, but somehow the ZED SDK crashed. After this, It wasn't work.
the following information is about ZED Diagnostic:
`{`
 `   "Camera Test": {`
  `      "ZEDCount": 0,`
 `       "error": [`
  `          "<b>Camera not detected</b> <br/> Make sure the camera is plugged in or try another USB 3.0 port."`
 `       ]`
 `   },`
 `   "Graphics Card": {`
      `  "deviceCount": 1,`
     `   "deviceDriverVersion": 9000,`
       ` "devices": [`
         `   {`
              `  "arch": "Maxwell",`
         `       "computeCapability": "5.0",`
          `      "cores": 640,`
        `        "name": "GeForce GTX 850M",`
        `        "totalMemoryBytes": "2100232192",`
       `         "totalMemoryMB": 2002.9375`
       `     }`
      `  ],`
      `  "initResult": 0`
   ` },`
 `   "Processor": {`
   `     "OS": "Ubuntu 16.04.6 LTS ",`
     `   "avxSupported": true,`
     `   "coreCount": "4",`
    `    "cpu": " Intel(R) Core(TM) i5-4200H CPU @ 2.80GHz",`
     `   "datetime": "2019-05-09 09時09分48秒",`
  `      "hyperThreading": "1",`
   `     "motherboard": "X550JK\n, ASUSTeK COMPUTER INC.\n",`
    `    "ramCapacity": "8.242299",`
   `     "ramUsage": "",`
   `     "ramUsed": "3.471548",`
    `    "threadCount": "8",`
     `   "valid": [`
       `     "<b>Processor: </b>  Intel(R) Core(TM) i5-4200H CPU @ 2.80GHz",`
     `       "<b>Motherboard: </b> X550JK\n, ASUSTeK COMPUTER INC.\n"`
     `   ]`
  `  },`
   ` "USB": {`
     `   "CorruptedFirmware": false,`
    `    "USBList": [`
      `      {`
       `         "USB_path": "/1/3",`
        `        "idProduct": "0xa0d6",`
       `         "idVendor": "0x04d9"`
        `    },`
      `      {`
      `          "USB_path": "/1/1/1",`
        `        "idProduct": "0x2210",`
       `         "idVendor": "0x2109"`
      `      },`
       `     {`
       `         "USB_path": "/1/1",`
       `         "idProduct": "0x2811",`
       `         "idVendor": "0x2109"`
       `     },`
       `     {`
             `   "USB_path": "/1",`
            `    "idProduct": "0x8000",`
             `   "idVendor": "0x8087"`
       `     },`
      `      {`
             `   "USB_path": "/1/3",`
           `     "idProduct": "0x57b4",`
            `    "idVendor": "0x0bda"`
         `   },`
         `   {`
           `     "USB_path": "/1/1",`
           `     "idProduct": "0x3414",`
            `    "idVendor": "0x13d3"`
         `   },`
         `   {`
             `   "USB_path": "/1",`
              `  "idProduct": "0x8008",`
               ` "idVendor": "0x8087"`
     `       }`
    `    ],`
     `   "ZEDDetected": false,`
     `   "notTested": [`
     `       "Please connect a camera to test the USB connection."`
      `  ]`
  `  },`
`"ZED SDK": {`
  `      "CUDA Toolkit version": "V9.0.176",`
  `      "DiagnosticZEDSDKVersion": "2.8.0",`
    `    "InstalledZEDSDKVersion": "Unknown",`
   `     "SMI": "(SMI) :     Performance State               : P8",`
   `     "initResult": 0,`
   `     "loaded": true`
 `   }`
`}`

Thanks.

**Comment by obraun-sl** [comment]
Please contact the support at support@stereolabs.com for a firmware upgrade issue.
