### ISSUE TITLE
ZED Explorer not opening

### ISSUE THREAD

**Issue by AmbarishGK** [stereolabs/zed-examples#149]
I am stuck not able to run the zed explorer with jetson nano developer kit. I have successfully installed the ZED SDK manager for it but I keep getting this error. 
![eoore](https://user-images.githubusercontent.com/23191860/58416082-165ea400-809e-11e9-8d75-b4094d0d45c4.png)

So how do I open the explorer and start working with depth caemera?

**Comment by nesnes** [comment]
Hi, it seems that the issue comes from a typo in your command.
`./ZED\Explorer` should be `./ZED\ Explorer` (with a space after the `\`)

**Comment by AmbarishGK** [comment]
Heyy @nesnes , thanks for that. 
I solved it by making changing the filename to ZED_Explorer and the file executable using
`chmod +x  ZED_Explorer`
`./ZED_Explorer`
It worked!!
