### ISSUE TITLE
Conan package for ZED sdk

### ISSUE THREAD

**Issue by orshefi** [stereolabs/zed-examples#153]
Hi guys,

We are working with Conan package manager for C++/C application and its a great way to produce system-wide dependency management and ABI compatibility for code reusability in C++ and C (whom of you familiar with this particular difficulty in large scale core projects).

Link for your impression - https://docs.conan.io/en/latest/introduction.html

Conan users are a growing community and I think its much of a use for you to deliver the ZED SDK as a Conan package to the users (you can package only artifacts and post it on Bintray for the common to use with your cameras) 

Please consider this matter as it would make a lot of your user's lives (especially in robotics field)
much easier.

**Comment by adujardin** [comment]
Thanks for sharing this.
I can definitely see how Conan package for the SDK, and a dependency management improvement in general would be useful. 
While that feature isn’t currently in our development roadmap, we'll keep this in mind for potential future improvements.
