### ISSUE TITLE
Export SVO file to avi UNRECTIFIED

### ISSUE THREAD

**Issue by FabianAC07** [stereolabs/zed-examples#154]
Hello all, 

Is there a way to export the SVO file video to .avi  WITH OUT rectification?

Thanks!

**Comment by obraun-sl** [comment]
Hi,
Yes you can change the VIEW_MODE of retrieveImage (https://github.com/stereolabs/zed-examples/blob/master/svo%20recording/export/src/main.cpp#L159) and select VIEW_LEFT_UNRECTIFIED instead of VIEW_LEFT for example.

**Comment by FabianAC07** [comment]
Hi @obraun-sl, 

I have made the changes on the main.cpp file in the lines 159 and 163. 

Now while I am trying to build the file in CMake I get the same error as many other users: 

![image](https://user-images.githubusercontent.com/47305059/59522276-3c58b680-8e9c-11e9-9f26-b6f875c3f1c7.png)

I followed these issues where they had the same problem: 
1. https://github.com/stereolabs/zed-examples/issues/21
2. https://github.com/stereolabs/zed-examples/issues/127

As you suggested on issue 127, I manually changed the **OpenCV_CONFIG_PATH** to my installed version of OpenCV 3.4.5,`C:\OpenCV-3.4.5\opencv-3.4.5\build` as follow:

![image](https://user-images.githubusercontent.com/47305059/59522590-0ec03d00-8e9d-11e9-939e-5b3ad3fbea3f.png)

When I hit Configure bottom again, I get the same error. 

![image](https://user-images.githubusercontent.com/47305059/59522686-48914380-8e9d-11e9-9263-8506f145d775.png)

How to solve this? I am not an expert on programming, so any help would be appreciated!
