### ISSUE TITLE
The image is inverted and the color is not normal.

### ISSUE THREAD

**Issue by guan4286** [stereolabs/zed-examples#161]
My operate system: Ubuntun 16.04 cuda9.0 zed_sdk2.8.
when I open ZED Explorer ,I recieved the following image ：

**Comment by guan4286** [comment]
![Screenshot from 2019-07-13 21-40-52](https://user-images.githubusercontent.com/34204574/61172492-b6717d80-a5b7-11e9-9285-a744ab495578.png)

**Comment by guan4286** [comment]
![Screenshot from 2019-07-13 21-40-52](https://user-images.githubusercontent.com/34204574/61172494-cd17d480-a5b7-11e9-9da7-358a6663aeca.png)

**Comment by guan4286** [comment]
how should to solve this problem ？

**Comment by guan4286** [comment]
![Screenshot from 2019-07-13 22-11-43](https://user-images.githubusercontent.com/34204574/61172725-3c42f800-a5bb-11e9-8cd4-53911a3c4b8a.png)
this is my cuda and nvdia

**Comment by obraun-sl** [comment]
This comes from a non compatible OpenGL driver version (GLSL error).
Make sure that opengl driver (mesa) are installed or during NVIDIA driver installation, make sure that it installs the opengl library.
