### ISSUE TITLE
.conf files overwriting itself

### ISSUE THREAD

**Issue by amaanda** [stereolabs/zed-examples#163]
I calibrated the cameras using the ZED Calibration Tool from 2.7.1, and then when running the ZED API 2.7.1, with the calibrated files on the correct path (C:\ProgramData\Stereolabs\settings), the files are getting overwritten for some reason. Any hints on what might be causing this problem?

**Comment by adujardin** [comment]
This issue was fixed in 2.8.2.
It's not actually overwritten, only open and saved (without any modifications). It was a bug in the destructor that would call "write" even if no changes occurred. The concurrent access could, therefore, leads to undefined behavior.

**Comment by amaanda** [comment]
Got it. Thanks!
