### ISSUE TITLE
On Ubuntu 18 with CUDA 10.1 fail: "ERROR: Found Cuda 9.1 but the ZED SDK requires 10.0"

### ISSUE THREAD

**Issue by EmilPi** [stereolabs/zed-examples#164]
CUDA is installed in /usr/local/cuda10-0.
Computer hardware is AMD Ryzen 2700X + NVidia RTX 2080.
On this PC, neural networks libraries successfully work with CUDA 10.1.

**Comment by adujardin** [comment]
Unfortunately, there's currently no compatible version of the ZED SDK with CUDA 10.1, only CUDA 10.0.
They are not binary compatible, the required version must exactly match.

**Comment by EmilPi** [comment]
For those who will experience this kind of problems, on fresh ubuntu system make sure to follow this guide until `sudo apt-get install cuda` command: https://medium.com/@zhanwenchen/install-cuda-10-1-and-cudnn-7-5-0-for-pytorch-on-ubuntu-18-04-lts-9b6124c44cc
