### ISSUE TITLE
How to get frame per second while processing svo file?

### ISSUE THREAD

**Issue by rishabh700** [stereolabs/zed-examples#166]
Hi, I would like to calculate the speed at which the processing is done on the .svo file. Hence, I need to calculate and display the frame per second value? Any idea how can I do that?

**Comment by obraun-sl** [comment]
Hi,

You have access to 2 functions in the SDK to calculate the FPS : 

- `getCameraFPS()` will give you the FPS based on the image's timestamp recorded in the SVO file. 
For example, if you have recorded in 720p60, it should gives 60fps if there was no frame dropped in the recording. Less if you have some drops.

- If SVO file is played in real time mode, `getCurrentFPS()` will give you the FPS based on the time between 2 grab() call. Basically, if you are doing a lot of processing after grab() has returned success, it will impact the FPS returned. That's more linked to the FPS of the application. If the SVO is not played in real time mode (InitParameters), it will be similar to getCameraFPS
