### ISSUE TITLE
Crop the frame of an already recorded video

### ISSUE THREAD

**Issue by pratikborhade1** [stereolabs/zed-examples#17]
Hey, so I have recorded a few videos with the ZED cameras. Due to the space problem, I had to record them with one object in the view which I do not want to be in the video. I would like to crop that part from the frame which is at the bottom(maybe 80 pixels heightwise) before converting it to get the depth map. Is there a way I can do this ?

**Comment by adujardin** [comment]
Hi,
Unfortunately, you can't crop or process the image *before* computing the depth map. However, nothing stops you from cropping the image and the depth map after the fact.
