### ISSUE TITLE
Issues with depth data

### ISSUE THREAD

**Issue by sriyan983** [stereolabs/zed-examples#172]
Attached are screenshots of the output.

I am using pytorch and darknet with yolov3-SPP. You can check this repo to understand the implementation.
https://github.com/ultralytics/yolov3.

Following is my code to detect an object from a ZED feed and use the MEASURE XYZ to get the distance to object.
https://pastebin.com/UwRAyj8X

[Depth calculation logic can be seen: getObjectDepth()]

The person standing further seems to be correct but the one sitting and working (me), the distance results are too inaccurate (+1.5m).

Also I see the depth data to be too fluctuating. How accurate is it supposed to be?

Can you please check the code and see if I am doing something wrong or this is how it is supposed to be?

![Screenshot from 2019-08-29 21-09-07](https://user-images.githubusercontent.com/4582315/63955548-8405dc00-caa2-11e9-928f-24e0190c0dba.png)
![Screenshot from 2019-08-29 21-09-18](https://user-images.githubusercontent.com/4582315/63955549-8405dc00-caa2-11e9-84ea-6dbf13991c29.png)

**Comment by adujardin** [comment]
You're currently using the fastest, and therefore less robust depth mode. You can replace `sl.DEPTH_MODE.DEPTH_MODE_PERFORMANCE` l.248 by `sl.DEPTH_MODE.DEPTH_MODE_ULTRA`. It's heavier to compute but the accuracy is increased.

To get an idea of the depth quality, you can use the DepthViewer tool which includes a 3D view of the point cloud with different settings to see the effect.

The code for depth extraction seems correct. However, it is focused on the center, you could try to sample a larger area (and skip some pixels, like 1 every 4 pixels) to get a more robust value.
Some more advanced method would be to compute the depth histogram on the ROI defined by the box.

**Comment by sriyan983** [comment]
Thanks a bunch for your response. I shall try the same and post the results.

**Comment by rishabh700** [comment]
You can also try to filter the depth values inside the sample area based on the confidence threshold values and then take the median of all the x,y,z values.
