### ISSUE TITLE
getIMUData returns irregular timestamps

### ISSUE THREAD

**Issue by svolodarskiy** [stereolabs/zed-examples#174]
Hi,

To clarify things I've created a sample: [main.cpp.zip](https://github.com/stereolabs/zed-examples/files/3574784/main.cpp.zip).

The idea is to call getIMUData(..., sl::TIME_REFERENCE_CURRENT) in a tight loop. In this case getIMUData returns the same IMU reading several times (as expected). The sample code waits for a moment when IMU data timestamp changes and prints an interval between two sequential IMU readings. The sample accumulates 2000 different IMU readings and then prints average interval.
My expectation of the sample was to produce intervals close to 125000 ns (corresponding to the IMU 800Hz frequency).
But an actual execution of the code on Jetson Nano has produced unexpected results: intervals between IMU readings are aligned to integer milliseconds (1ms or 2ms): """
>    #: interval between sequential IMU data (ns)
>    0:   1005589
>    1:    949181
>    2:   1169706
>    3:   1816592
>    4:   1007047
>    5:   1065798
>    6:    901108
>    7:   2010240
>    8:    999287
>    9:   1000693
> 1990:   1051631
> 1991:    970120
> 1992:   1974823
> 1993:   1011057
> 1994:   1002829
> 1995:    996422
> 1996:   1993208
> 1997:    999912
> 1998:   1003974
> 1999:    999443
> 
> average interval (ns): 1265986.757000
""".

Could you please clarify how can I get more precise IMU data timestamps?
Thank you.

**Comment by luan1412167** [comment]
Hi @svolodarskiy 
 I got same result but don't understanding why? Did you clarify it?
