### ISSUE TITLE
Extracting (x,y,z) coordinates from a SVO file

### ISSUE THREAD

**Issue by avnishks** [stereolabs/zed-examples#183]
Hi,

I was hoping to get some pointers on how to go about doing the following:
I have a few SVO files saved. The video is of a moving object that I am interested in knowing the position of, in world coordinate system. I know the location of this object in the camera frame (`x_pixel, y_pixel`) using another algorithm. So, how can I retrieve these world coordinate position (`x, y, z`) values for these (`x_pixel, y_pixel`) points? 
(I'm using the python API)

**Comment by obraun-sl** [comment]
Hi,

Note : If using the python API, best would be to post your question in the python repository (zed-python-api).

I think that what you want to do is what is show on the depth sensing tutorial here : 
https://github.com/stereolabs/zed-python-api/blob/master/tutorials/depth_sensing.py

```
            zed.retrieve_measure(point_cloud, sl.MEASURE.MEASURE_XYZRGBA)
            err, point_cloud_value = point_cloud.get_value(x_pixel, y_pixel)
            x = point_cloud_value[0]
            y = point_cloud_value[1]
            z = point_cloud_value[2]
```
