### ISSUE TITLE
ZEDProject/zed-examples-master/camera streaming/receiver,运行程序提示的ip：port是什么？

### ISSUE THREAD

**Issue by peter2527** [stereolabs/zed-examples#184]
![2019-10-03 12-10-27屏幕截图](https://user-images.githubusercontent.com/43690556/66098885-fe140e00-e5d6-11e9-8f4f-135cbb530a80.png)

**Comment by obraun-sl** [comment]
Hi,
You need to set your IP first : in local, you can use 127.0.0.1

`$ ./ZED_Streaming_Receiver 127.0.0.1`

**Comment by reginalluna** [comment]
Hi ya,
 
Check this code by the part of USING A STREAM AS SDK INPUT at [ZED manuscript](https://www.stereolabs.com/docs/video/streaming/); you have to set an IP address to the camera first. 

`# Set the input from stream
init = sl.InitParameters()
init.set_from_stream("127.0.0.1", 30000)`
