### ISSUE TITLE
Camera streaming and position tracking same time

### ISSUE THREAD

**Issue by mesimolnar** [stereolabs/zed-examples#185]
Hi I am working with Zed mini camera and nvidia jetson tx2 and using your cpp example library.
My question is the following:
Is it possible to get camera stream and position information at the same time ?

**Comment by obraun-sl** [comment]
Sure. Streaming input is just another input mode, like LIVE or SVO. Therefore you can call getPosition() after grab() .

**Comment by mesimolnar** [comment]
Thank you
