### ISSUE TITLE
depth algorithm

### ISSUE THREAD

**Issue by soldierofhell** [stereolabs/zed-examples#187]
Hi, what kind of algorithm stands behind disparsity estimation? Is it DNN- based? Are there any benchmark with eg. classic OpenCV or KITTI leaderboard? Regards,

**Comment by snakehaihai** [comment]
I`m not working with ZED company, but I study stereo as phd research for a while. But based on my understanding and observation. They are using SGM based method with very large P1 and P2. As for cost/Cost aggregation, Cant tell that it is 3 Way sgm or census transform variant. But I dont think it is things like CNN or Daisy Descriptor as those method are way too slow. Hope this gives you some cue.

**Comment by soldierofhell** [comment]
Thank you for the info. By NVIDIA you mean their VisionWorks: https://developer.nvidia.com/embedded/visionworks ? Is the code available somewhere (I couldn't find it)?

By the way, what is the reference implementation of SGM? I found a few on github

**Comment by snakehaihai** [comment]
yes visionworks. previously it is nvxio. now might be a bit different. i think you can find the detail reference in their webside

**Comment by soldierofhell** [comment]
Thank you. I found nvx_demo_stereo_matching example in VisionWorks
