### ISSUE TITLE
Cannot open SVO file

### ISSUE THREAD

**Issue by hankh1105** [stereolabs/zed-examples#188]
Hi, I was trying out the SVO  export utility  with the command **ZED_SVO_Export "path/to/file.svo" "path/to/output/file.avi" 0**, and what I get everytime was 

> ZED (Init) >> ERROR: Cannot load SVO file. Check that the path of the SVO is correct, avoid white spaces in filename, add ".svo" extension to filename.
> INVALID SVO FILE

I made sure the SVO file does exist at the correct path. I tried opening the file using  ZED Explorer. Turns out, it also gave me   **** [SVO] Hardware compression (NVENC) available **
FAILURE : Didn't manage to open svo file INVALID**.

I installed CUDA  10.1 and ZED SDKv2.8.0.

**Comment by obraun-sl** [comment]
It may be possible that the SVO file got corrupted. Try to use the -repair option of ZED SVOEditor.

**Comment by hankh1105** [comment]
I tried SVOEditor.exe -repair input.svo and I get

>  'SVOEditor.exe' is not recognized as an internal or external command,
> operable program or batch file.

Then I tried **"ZED  SVOEditor".exe -repair input.svo**, it didn't give errors but didn't generate a repaired file either.

**Comment by obraun-sl** [comment]
It may be a permission issue then. Try to run your program with admin rights

**Comment by impermanD** [comment]
May your file path include some utf-8 code
