### ISSUE TITLE
Translation & Rotation vary largely on multiple runs of same .svo file

### ISSUE THREAD

**Issue by Gstevenson3** [stereolabs/zed-examples#189]
This problem exists in the C++ Positional Tracking demos and reading values straight out of the python-api. 

I run the same .svo file where I traversed a few hundred meters and the values I get from the api or in the C++ example change each time I run the file.

Clearly, a visual odometry algorithm is getting re-run each time and has different results. I need to get a consistent answer. Is there a way to get the inputs to the VO algorithm? I can't have the translation and rotation vary every time I replay a file.

**Comment by obraun-sl** [comment]
Hi,
If not done, Try to disable the self calibration in the InitParameters. It could lead to small differences in the image and therefore makes the VO behaves a little bit differently. 
What is the magnitude of the differences you have ?
