### ISSUE TITLE
depth sensing 

### ISSUE THREAD

**Issue by kehlaaa** [stereolabs/zed-examples#190]
hello, i have installed the SDK,  when i try to run the depth sensing  example, only the RESOLUTION_VGA could be used. If i init the camera with other resolution params ,such as RESOLUTION_HD2K, RESOLUTION_HD1080, RESOLUTION_HD720, the program occurs error: cannot initialize the camera. Try another  resolution. 
My program init the params below:

initParameters.depth_mode = DEPTH_MODE_MEDIUM; 
initParameters.coordinate_units = UNIT_MILLIMETER; measurements)
initParameters.camera_resolution = RESOLUTION_HD2K;
initParameters.sdk_verbose = true;

**Comment by obraun-sl** [comment]
Hi,
Can you specify the camera model (ZED or ZED-M), the SDK version and the OS  you are using. 
Try the resolution with ZED Explorer to check if they are availalble. Make sure the camera is connected on a USB3.0 port otherwise only VGA resolution is available.

**Comment by kehlaaa** [comment]
i found that the camera is connected on a USB2.0 port, so i change to another computer with usb3.0 port, then the  high RESOLUTION can be used. Thanks for your help.
