### ISSUE TITLE
Use the stream to a fifo

### ISSUE THREAD

**Issue by mesimolnar** [stereolabs/zed-examples#191]
Hi I would like to use the streaming option to get video output and data output also.
I could get the information when I use it on my Jetson, but I would like to push the video data to a fifo as an input of gstreamer. But if I try it with opencv imencode it gets an error cause the sl::Mat is not compatible with the input of the imencode.
Can you help me with this, how can I solve it.

Thank you

**Comment by obraun-sl** [comment]
Hi,
You need to use a cv::Mat in OpenCV functions. Therefore you need to convert sl::Mat to cv::Mat.
This function is exposed here for example : 
https://github.com/stereolabs/zed-examples/blob/master/svo%20recording/playback/include/utils.hpp#L62
