### ISSUE TITLE
Concatenating multiple sl::mat images

### ISSUE THREAD

**Issue by kushal2507** [stereolabs/zed-examples#193]
Is there a method to concatenate 2 or more sl::mat images? Something similar to cv::hconcat or cv::vconcat??I dont want to convert my images to cv::Mat images.

I am recording from 2 ZED cameras and want to be able to view the images in a single window.

**Comment by Myzhar** [comment]
Hi @kushal2507 
You can directly retrieve SIDE-BY-SIDE images using `VIEW_SIDE_BY_SIDE` as parameter in `retrieveImage`

**Comment by kushal2507** [comment]
@Myzhar Thank You for the quick response. I want to concatenate only the left image of both the cameras. From what I understood from the documentation, using VIEW_SIDE_BY_SIDE shows the left and right image of the same camera. 
I am recording each camera using multi-threads, similar to what has been done in the zed-multi-camera repository

**Comment by Myzhar** [comment]
Ah, sorry for the misunderstanding.
The only way to achieve your purpose is to create a new image with same height and double width and copy the data line by line using `memcpy` or `std::copy`
