### ISSUE TITLE
support for CUDA 10.1/2?

### ISSUE THREAD

**Issue by jwdinius** [stereolabs/zed-examples#200]
Any updates on when CUDA>10.0 will be supported by the SDK?

![Screenshot from 2019-12-27 10-01-21](https://user-images.githubusercontent.com/20928867/71527425-3c486300-2890-11ea-9683-42077536ddb4.png)

**Comment by figo-figo** [comment]
only support for CUDA 10.0

**Comment by adujardin** [comment]
The [2.8.5 is released](https://www.stereolabs.com/developers/release/) and now also support CUDA 10.2

**Comment by madoxnet** [comment]
The latest SD images for Jetson Nano use Cuda 10.2, the latest ZED SDK on https://www.stereolabs.com/developers/release/ doesn't seem to support it.  Its quite annoying to manually install 10.0 and finding an old SD image on Nvidia's site is extremely difficult.

**Comment by obraun-sl** [comment]
The support for Jetpack 4.4 will be release with the ZED SDK 3.2 in a few days .
Jetpack 4.3 ( with cuda 10.0) is still the official stable release and you can download it directly here : 
https://developer.nvidia.com/jetpack-43-archive

**Comment by spiderkeys** [comment]
Just checking in, since it has been a week since the last comment. Is there an updated timeframe for when SDK 3.2 will be available? Thanks.
