### ISSUE TITLE
Can't install ZED SDK.

### ISSUE THREAD

**Issue by machenxiang** [stereolabs/zed-examples#204]
Note, selecting 'libpng12-dev' instead of 'libpng-dev'
Package ttf-mscorefonts-installer is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
But i can't open ZED explor.

**Comment by obraun-sl** [comment]
Hi,
What is the error you have when you try to open ZED Explorer ?

**Comment by machenxiang** [comment]
It can't b open the ZED explorer. It doesn’t have any error.

Oliver Braun <notifications@github.com>于2020年1月20日 周一15:41写道：
