### ISSUE TITLE
SVO_Recording does not convert .svo to .avi or .png

### ISSUE THREAD

**Issue by RSKothari** [stereolabs/zed-examples#21]
For some reason, it doesn't convert an input .svo video to a .avi video or .png image files. It writes out a few .png images but they are all black.

Is it because the ZED SDK wasn't compiled correctly?

**Comment by WASCHMASCHINE** [comment]
Have you inspected the images? Are they pitch black, like 0?

**Comment by RSKothari** [comment]
Hey @WASCHMASCHINE , 
Yes, the images are pitch black, as in 0. For some reason, The code runs smoothly and outputs nothing.

**Comment by RSKothari** [comment]
@WASCHMASCHINE Bump.

**Comment by WASCHMASCHINE** [comment]
Post your code and add more info: Which SDK version etc.

**Comment by RSKothari** [comment]
I found the fix to the solution. I used cmake-gui to look at the variables and the by default setting for OpenCV_DIR was pointed to the cmake folder in my opencv folder. I changed it to the build directory and manually set the flag OpenCV_FOUND to 1. Export and Playback work alright now. Thanks @WASCHMASCHINE !
