### ISSUE TITLE
ZED_SVO_Export to sequence stuck at 99 percent

### ISSUE THREAD

**Issue by gaopinghuang0** [stereolabs/zed-examples#211]
The .svo file is recorded via ZED-unity (plugin v2.8.2). Then I use `ZED_SVO_Export.exe <filename>.svo output_folder\ 2` to convert into sequence of images. It will get stuck at 99%, as shown in the screenshot. However, the images are already generated in the output_folder.

ZED SDK version: 2.8.5
Windows 10

![image](https://user-images.githubusercontent.com/9276774/74059108-4637a880-499c-11ea-8185-ec6c42f249bb.png)

**Comment by kalyan0510** [comment]
+1 
I am facing very similar issue on Ubuntu 18.04
with 3.5-gl-devel-cuda10.0-ubuntu18.04 docker env.

**Comment by obraun-sl** [comment]
Can you check here : 
https://github.com/stereolabs/zed-examples/issues/379
Make sure you are pulling the last version
