### ISSUE TITLE
Can I use 3d object detection and plane detection examples by ZED1?

### ISSUE THREAD

**Issue by noah003** [stereolabs/zed-examples#216]

**Comment by obraun-sl** [comment]
Hi,
The plane detection is compatible with any ZED model (ZED,ZED-M, ZED2). 
The object detection module is only available with ZED2 camera.

**Comment by A7ocin** [comment]
Hi. Why is the object detection module only compatible with the ZED 2? I mean, technically speaking

**Comment by kaixindelele** [comment]
> Hi. Why is the object detection module only compatible with the ZED 2? I mean, technically speaking

I'm also curious why it can't be used...
