### ISSUE TITLE
SDK 3.0.3: Enable/disable recording fails after first recording

### ISSUE THREAD

**Issue by JesperChristensen89** [stereolabs/zed-examples#224]
In the newest update, the recording issue when streaming is fixed. However, if you wish to split your recording in multiple files it fails after having recorded the first file. 

Example:

enable recording on file1.svo and record say 100 frames, then disable recording, change `rec_params.video_filename` and enable recording again. This new file will only become 280 bytes large, while the initial file records just fine.

**Comment by obraun-sl** [comment]
Hi,

Issue has been identified and will be fixed in next release (3.1)

Best,
OB

**Comment by prelee** [comment]
I don't know if it helps, I ran into this problem as well, a temporary solution (until 3.1) that is pseudo working for me is to actually close the camera and re-open it, then you can save multiple files, however it takes time and you lose recording for the time in between closing and re-opening.

**Comment by JesperChristensen89** [comment]
@obraun-sl Any news as to when you will release the next version?

**Comment by obraun-sl** [comment]
The SDK 3.1.0 (with the fix) has been released : 
https://www.stereolabs.com/developers/release/
