### ISSUE TITLE
The code do not work,why?

### ISSUE THREAD

**Issue by DreamsZM** [stereolabs/zed-examples#23]
`cv::gpu::GpuMat inputDepthMat_GPU, inputColorMat_GPU;
	inputDepthMat_GPU.create(cv::Size(inputDepthMat_ZED.getWidth(), inputDepthMat_ZED.getHeight()), CV_8UC4);
	size_t pitch;
	cudaMallocPitch((void**)inputDepthMat_GPU.data, &pitch, inputDepthMat_GPU.cols*sizeof(uchar), inputDepthMat_GPU.rows);
	cudaMemcpy2D(inputDepthMat_GPU.data, pitch, inputDepthMat_ZED.getPtr<sl::uchar4>(sl::MEM_GPU), inputDepthMat_ZED.getStepBytes(sl::MEM_GPU),
		         inputDepthMat_ZED.getWidth()*sizeof(sl::uchar4), inputDepthMat_ZED.getHeight(), cudaMemcpyDeviceToDevice);`

**Comment by sl-braun** [comment]
What is inputDepthMat_ZED (how do you get it) ? Check the return value of cudamemcpy (it will indicate a cudaError_t)
