### ISSUE TITLE
there's no model data in resources folder

### ISSUE THREAD

**Issue by DasomKong** [stereolabs/zed-examples#236]
i'm using win 10 and trying to develop contents using object detection.

when i execute sample binary of zed-objectdetection, it throws corrupted sdk installation and no model data.

so i checked if there's no data in resources folder, and there aren't.

i'm using zed sdk 3.1.2 the lastest one, cuda 10.2.

graphic card : nvidia geforce gtx 1050.

**Comment by DasomKong** [comment]
my device is zed 2

**Comment by 13621294557** [comment]
ZED 有什么功能

**Comment by mgzjzzhang** [comment]
I have the same problem on nvidia Xavier,I reinstall many times but the resources has no model
