### ISSUE TITLE
How can I use the API without CUDA?

### ISSUE THREAD

**Issue by sennnnn** [stereolabs/zed-examples#237]
After buying the zed camera, I feel really awkward. Because I don't have a nvidia graphics adapter. So how should I do if i want to use the zed camera.

**Comment by obraun-sl** [comment]
CUDA and therefore a NVIDIA graphic card is required to use the ZED SDK. 
Without CUDA, you can use the camera as a 3D camera, using open source library (such as OpenCV).
You can check our example here : 
https://github.com/stereolabs/zed-opencv-native

**Comment by sennnnn** [comment]
Ok, I get it. Thank you.
