### ISSUE TITLE
What'more, I wanna know how can you convert the 2D coordinate to 3D coordinate.

### ISSUE THREAD

**Issue by sennnnn** [stereolabs/zed-examples#238]

**Comment by obraun-sl** [comment]
There is an example of convert 2D pixels coordinates to 3D world coordinates here  : 
https://github.com/stereolabs/zed-examples/blob/master/tutorials/tutorial%203%20-%20depth%20sensing/cpp/main.cpp#L67

Using the ZED SDK API.

**Comment by sennnnn** [comment]
Thank you.

**Comment by FeiSong123** [comment]
What I want to make sure is that as long as the xy filled here is the object xy in the left or right view, I can get the 3d point of the target object, right? Or do we have to deal with xy?

**Comment by Myzhar** [comment]
Hi @FeiSong123 
please do not reply to a closed issue. The GitHub issue is for reporting bugs and feature requests.
Please consider posting on the Stereolabs forum or search the Support page for a solution, like this:
https://support.stereolabs.com/hc/en-us/articles/4554115218711-How-can-I-convert-3D-world-coordinates-to-2D-image-coordinates-and-viceversa-

**Comment by FeiSong123** [comment]
Sorry, I'll try it.
