### ISSUE TITLE
dataset svo

### ISSUE THREAD

**Issue by omar-Fouad** [stereolabs/zed-examples#239]
Hi
would you please tell me if i can download svo dataset for testing example
thanks

**Comment by obraun-sl** [comment]
Hi. You can find some SVO samples here : 
https://www.stereolabs.com/download_327af3/SVO_samples/

We are working to add more SVOs into public access.

**Comment by omar-Fouad** [comment]
Merci beaucoup

**Comment by jonasdv97** [comment]
@obraun-sl, I cannot access the SVO sample. I would like to test it as well.

Thanks in advance.

**Comment by emeQee** [comment]
> Hi. You can find some SVO samples here :
> https://www.stereolabs.com/download_327af3/SVO_samples/
> 
> We are working to add more SVOs into public access.

The SVO Sample links died and redirect to the front page. Do you have current links? I would appreciate it very much.

**Comment by obraun-sl** [comment]
While we are migrating the SVO samples to the website you can find the links below : 

SVO samples : 
ZED : https://download.stereolabs.com/assets/svo_samples/wall
ZED : https://download.stereolabs.com/assets/svo_samples/sofa
ZED : https://download.stereolabs.com/assets/svo_samples/well
ZED2 : https://download.stereolabs.com/assets/svo_samples/ZED2_Lake_H264 (*_H265 for H265 version)
ZED2 : https://download.stereolabs.com/assets/svo_samples/ZED2_Street_H264 (*_H265 for H265 version)
ZED2 : https://download.stereolabs.com/assets/svo_samples/ZED2_Runners_H264 (*_H265 for H265 version)

Mesh from SVO samples : 
https://download.stereolabs.com/assets/mesh_samples/wall
https://download.stereolabs.com/assets/mesh_samples/sofa
https://download.stereolabs.com/assets/mesh_samples/well

**Comment by ymtoo** [comment]
I'm not able to read the SVO samples, e.g.,
```
>>> import pyzed.sl as sl
>>> zed = sl.Camera()
>>> input_path = "sofa.svo"
>>> init_parameters = sl.InitParameters()
>>> init_parameters.set_from_svo_file(input_path)
>>> zed = sl.Camera()
>>> err = zed.open(init_parameters)
# get stuck here
```
My setup is:
- Ubuntu 20.04.3
- ZED SDK 3.6.2
