### ISSUE TITLE
ZED connection -> NO GPU DETECTED

### ISSUE THREAD

**Issue by tigerJkLee** [stereolabs/zed-examples#241]
Hi, thank you for helping me.

I am trying to launch zed_wrapper node.
I followed "https://www.stereolabs.com/docs/ros/".

My desktop specifications
- ubuntu 18.04
- ROS melodic 
- NVIDIA GeForce GTX 1050 Ti
- CUDA 10.2

when i command
$ roslaunch zed_wrapper zed2.launch
and the following errors are keep showing repeatedly
=======================================
...
[ INFO] [1588042833.636576341]:  *** Opening ZED 2...
[ INFO] [1588042834.100040526]: ZED connection -> NO GPU DETECTED
[ZED]ERROR: sl::Camera::Open has not been called, no Camera instance running.
in Camera.cpp : void sl::Camera::close() at 155 : cuda error [100]: no CUDA-capable device is detected.
in Camera.cpp : void sl::Camera::close() at 199 : cuda error [100]: no CUDA-capable device is detected.
[ INFO] [1588042836.310678265]: ZED connection -> NO GPU DETECTED
[ZED]ERROR: sl::Camera::Open has not been called, no Camera instance running.
in Camera.cpp : void sl::Camera::close() at 155 : cuda error [100]: no CUDA-capable device is detected.
in Camera.cpp : void sl::Camera::close() at 199 : cuda error [100]: no CUDA-capable device is detected.
...
======================================

it says it cant detect GPU, but i checked multiply that it has - NVIDIA GeForce GTX 1050 Ti.

please give me any answers please...
Thank you for reading.

**Comment by yike-chen** [comment]
I had the same thing with you. After I reboot the machine, it works well.
