### ISSUE TITLE
zedfu didn't give textures

### ISSUE THREAD

**Issue by omar-Fouad** [stereolabs/zed-examples#246]
hi
i used zed2 application zedfu it dosen't give me texture. it give only mesh . !!!
how to texture mesh thanks 
windows 10
cuda 10 
ram 16G 
Geforce 1060

**Comment by obraun-sl** [comment]
Before starting to mesh, go in the settings window and click on apply texture.
![zedfu_settings](https://user-images.githubusercontent.com/14200362/81651586-11bc0880-9433-11ea-9dd9-1de05db51864.png)

**Comment by omar-Fouad** [comment]
thanks

**Comment by omar-Fouad** [comment]
hi
is the source code of zedflu available ?
thanks again

**Comment by obraun-sl** [comment]
It' not, but the spatial mapping sample provides the same functions.
