### ISSUE TITLE
[ZED Explorer] white screen when trying to play an svo file

### ISSUE THREAD

**Issue by amaanda** [stereolabs/zed-examples#247]
any ideias on why this might happen? On this example I'm using zed 2.8.3 sdk, on a windows 10 machine.

<img width="1000" alt="Captura de Tela 2020-05-19 às 15 09 39" src="https://user-images.githubusercontent.com/20389222/82362892-718e5280-99e3-11ea-9f82-48afd4cbf60c.png">

**Comment by obraun-sl** [comment]
It looks like an opengl issue. 
Do you have the same issue with other tools such as ZED Depth Viewer ?
or in LIVE mode ?

**Comment by amaanda** [comment]
Yes, when I try opening the Depth Viewer I get the same blank screen.

**Comment by amaanda** [comment]
I tried reinstalling the SDK but it still won't work

**Comment by amaanda** [comment]
Apparently the opengl dll is in the folder... The weird thing is: when I use the snapshot button at the Explorer, the saved image is perfectly fine.

![image](https://user-images.githubusercontent.com/20389222/82480231-dca25c80-9aa9-11ea-82e0-69300ac11d1c.png)
