### ISSUE TITLE
qt example

### ISSUE THREAD

**Issue by omar-Fouad** [stereolabs/zed-examples#248]
hi
there any any example of using zed2 with qt interface !!!
thanks

**Comment by obraun-sl** [comment]
Hi,
Do you mean/want with qmake generator or use Qt libraries via cmakefile ?

**Comment by omar-Fouad** [comment]
hi
i mean use qt libraries "qtopengl, qtgui ..."
thanks for reply

**Comment by obraun-sl** [comment]
You can find an example here using qmake as makefile generator
https://github.com/obraun-sl/qtZEDViewer

**Comment by omar-Fouad** [comment]
hi again 
thanks for code  but   would you  tell me please how can i draw  spatial mapping on  opengl widget 
thanks again
