### ISSUE TITLE
Distance Measure

### ISSUE THREAD

**Issue by malith1992** [stereolabs/zed-examples#249]
Is there any possible way to get the real world distance between two points using the ZED2 camera using ZED python API

**Comment by obraun-sl** [comment]
Once you have the 2 points (3D points), you can calculate the euclidean distance like this : 

```
import math
distance = math.sqrt( ((p1[0]-p2[0])**2)+((p1[1]-p2[1])**2)+((p1[2]-p2[2])**2) )
```

where p1 and p2 are your 3D points.

**Comment by malith1992** [comment]
> Once you have the 2 points (3D points), you can calculate the euclidean distance like this :
> 
> ```
> import math
> distance = math.sqrt( ((p1[0]-p2[0])**2)+((p1[1]-p2[1])**2)+((p1[2]-p2[2])**2) )
> ```
> 
> where p1 and p2 are your 3D points.

Is the 3D point mean the out put of this function `point_cloud.get_value(x, y)` right ?

**Comment by obraun-sl** [comment]
Yes. You can get P1 and P2 like this : 
p1 = point_cloud.get_value(x1, y1);
p2 = point_cloud.get_value(x2, y2);

where x1,y1,x2,y2, must respect [0,Resolution]

See here : https://github.com/stereolabs/zed-examples/blob/master/tutorials/tutorial%203%20-%20depth%20sensing/python/depth_sensing.py#L72
