### ISSUE TITLE
Object detection module with Zed Mini

### ISSUE THREAD

**Issue by Tetsujinfr** [stereolabs/zed-examples#250]
hi
are you planning to make the Object detection module compatible with the ZED Mini? Why this module is only available for the ZED2, is there a hardware limitation on the ZED-M preventing object detection to work properly?
thanks

**Comment by obraun-sl** [comment]
There is some HW limitations for the ZED-M due to its small baseline and smaller FoV compared to ZED-M. Results will not work as expected, therefore object detection is limited to ZED2 which filled all those requirements.
