### ISSUE TITLE
doubt in camera stream example

### ISSUE THREAD

**Issue by svabhishek29** [stereolabs/zed-examples#252]
Hi, 

in the camera stream example a receiver is acquiring the data from the camera and is transmitting it to another location. i just want to know if we want depth data on the other location does the machine on the initial location have to have a GPU or does the machine at location 2 have to have a GPU?

Thanks

**Comment by obraun-sl** [comment]
Hi,
Both sender and receiver are using the ZED SDK , therefore they need a nvidia gpu on both sides. 
The encoding process also uses the GPU for real time compression.
