### ISSUE TITLE
3d point from depth data

### ISSUE THREAD

**Issue by svabhishek29** [stereolabs/zed-examples#253]
Hi, 

i wanted to know if we want 3D point do we need to have point cloud or can we get it from the depth data?

Thanks

**Comment by obraun-sl** [comment]
Hi,
The simpliest way is to get the point cloud that contains the 3D point (X,Y,Z). 
The depth data only contains the Z value. It's possible to convert the depth to point cloud by using the camera parameters (fx,fy,cx,cy)
You can see how to do it here : 
https://github.com/stereolabs/zed-3d-social-distancing/blob/master/src/cuUtils.cu#L31
