### ISSUE TITLE
How to get (x,y,z) coordinates from RGB images?

### ISSUE THREAD

**Issue by mm840511m** [stereolabs/zed-examples#255]
Hi,
I have already got some RGB images (ex. RGB(1), RGB(2)..., RGB(100)) from ZED 2, how to get (x,y,z) coordinates of each pixels?

**Comment by wangmh1116** [comment]
I have the same problem. Do you solve it ?

**Comment by P-yver** [comment]
Hi,
you can find a tuto [here](https://github.com/stereolabs/zed-examples/blob/master/tutorials/tutorial%203%20-%20depth%20sensing/cpp/main.cpp#L67). 
As long as the image and the point cloud are retrieved at the same resolution.
