### ISSUE TITLE
Can I get a spatial mesh map by streaming ?

### ISSUE THREAD

**Issue by Zgihu** [stereolabs/zed-examples#258]
We can see camera live video by streaming by SDK initial option, but can we get spatial mesh map by streaming ? 
How can I make it real?
I want to use ZED mini on drone , and watch spatial mesh map sent by flying drone in real time.

**Comment by obraun-sl** [comment]
Use the Spatial mapping sample and change the input to : 
`init_parameters.input.setFromStream(ip,port);`

**Comment by muraiyuya** [comment]
Okay.
So,how should I change the code and where to chang?
I'm pasting the "Spatial Mapping code" below.
-----------------------------------------------------------------------------------------------------
 if (sscanf(arg.c_str(),"%u.%u.%u.%u:%d", &a, &b, &c, &d,&port) == 5) {
            // Stream input mode - IP + port
            string ip_adress = to_string(a)+"."+to_string(b)+"."+to_string(c)+"."+to_string(d);
            param.input.setFromStream(sl::String(ip_adress.c_str()),port);
            cout<<"[Sample] Using Stream input, IP : "<<ip_adress<<", port : "<<port<<endl;
        }
        else  if (sscanf(arg.c_str(),"%u.%u.%u.%u", &a, &b, &c, &d) == 4) {
            // Stream input mode - IP only
            param.input.setFromStream(sl::String(argv[1]));
            cout<<"[Sample] Using Stream input, IP : "<<argv[1]<<endl;
        }
----------------------------------------------------------------------------------------------------------

**Comment by muraiyuya** [comment]
Okay.
So,how should I change the code and where to chang?
I'm pasting the "Spatial Mapping code" below.

-------------
if (sscanf(arg.c_str(),"%u.%u.%u.%u:%d", &a, &b, &c, &d,&port) == 5) {
// Stream input mode - IP + port
string ip_adress = to_string(a)+"."+to_string(b)+"."+to_string(c)+"."+to_string(d);
param.input.setFromStream(sl::String(ip_adress.c_str()),port);
cout<<"[Sample] Using Stream input, IP : "<<ip_adress<<", port : "<<port<<endl;
}
else if (sscanf(arg.c_str(),"%u.%u.%u.%u", &a, &b, &c, &d) == 4) {
// Stream input mode - IP only
param.input.setFromStream(sl::String(argv[1]));
cout<<"[Sample] Using Stream input, IP : "<<argv[1]<<endl;
}

**Comment by obraun-sl** [comment]
Since we already provide the way to use streaming input in the spatial mapping sample, you don't have to change anything. Just launch this way : 
$ ./ZED_Spatial_Mapping <ip>:port

For example, 
$ ./ZED_Spatial_Mapping 192.168.1.60:30000

**Comment by muraiyuya** [comment]
I see!
Thank you so much.

$ ./ZED_Spatial_Mapping 192.168.1.60:30000
Above comand should be at Receiver side?
How about Sender side?

**Comment by obraun-sl** [comment]
Receiver : 
$ ./ZED_Spatial_Mapping 192.168.1.60:30000

Sender  (no need to specify IP)
$ ./ZED_Streaming_Sender

**Comment by muraiyuya** [comment]
I see.
So at the Receiver side, which should I tipe "$ ./ZED_Spatial_Mapping 192.168....(port)" in the directory,
\spatial mapping\cpp\build 
or
 \camera streaming\receiver\cpp\build ???

**Comment by muraiyuya** [comment]
My receiver side is visual studio 2019, how can I represent the comand code ,$ ./ZED_Spatial_Mapping 192.168.1.60:30000?

**Comment by obraun-sl** [comment]
$ is just to indicate that it must run in a terminal...
On windows, the syntax will be more (in a terminal ) : 

`ZED_Spatial_Mapping.exe 192.168.1.60:30000`

**Comment by Zgihu** [comment]
I understand it now.
Thanks a lot!
