### ISSUE TITLE
Is it possible to change the range of spatial map closer? 

### ISSUE THREAD

**Issue by Zgihu** [stereolabs/zed-examples#259]
Is it possible to change the range of spatial map closer? (For example 0.10m-5m)
Initially, it seems difficult to make spatial mesh map at close range area ,like 0.10m -0.30m.

**Comment by muraiyuya** [comment]
Is it possible to change the range of spatial map closer? (For example 0.10m-5m)
Initially, it seems difficult to make spatial mesh map at close area ,like 0.10m -0.30m.
