### ISSUE TITLE
Cmakelist.txt cannot be found

### ISSUE THREAD

**Issue by dumbfk98** [stereolabs/zed-examples#26]
The source directory /"usr/local/zed/sample" does not appear to contain CMakeLists.txt.

I tried moving the Cmakelist from depth sensing to the source directory but it doesn't work.

Help please :((

**Comment by cosama** [comment]
I assume you figured that one out yourself by now, but maybe someone has the same question. The samples in that folder are independent of each other and the idea is to build them each separately. To build the first sample for example you do:

``
cd /sample/camera\ control/
mkdir build
cd build
cmake ../
``
