### ISSUE TITLE
Manual Calibration ZED Camera

### ISSUE THREAD

**Issue by Scarf195** [stereolabs/zed-examples#260]
Hi, I would be interested in using the ZED Camera for underwater application.
Is it possible to recalibrate the ZED Camera manually without using the Calibration Tool supplied by ZED SDK?

**Comment by obraun-sl** [comment]
You can use OpenCV stereo calibration toolbox and then export the value in the proper configuration format (in SN<XXX>.conf file)

**Comment by mpegew** [comment]
hi, for underwater do we have to use transparent dome on each of the lens, or a flat transparent panel is good enough? As the refractive index of light changes with medium change from glass to water etc.
