### ISSUE TITLE
retrieve image for unrectified left view

### ISSUE THREAD

**Issue by Alvin0629** [stereolabs/zed-examples#262]
Hi, 

I am using SDK 3.2 on win10 and python.   When reading data from the camera,
zed.retrieve_image(image_zed_left, sl.VIEW.LEFT)       **WORKS FINE!**
However, 
zed.retrieve_image(image_zed_left_unrect, sl.VIEW.LEFT_UNRECTIFIED)  
**returns this error:** TypeError: Argument 'py_mat' has incorrect type (expected pyzed.sl.Mat, got numpy.ndarray)
and 
zed.retrieve_image(image_zed_left_unrect, sl.VIEW.LEFT.UNRECTIFIED)
**returns AttributeError:** 'VIEW' object has no attribute 'UNRECTIFIED'
What's the correct parameter to read unrectified images? Thanks!

**Comment by Poutsh** [comment]
Hi,

I cannot reproduce your bug, is image_zed_left_unrect a ```pyzed.sl.Mat``` according to what the error says?
Can you try this snippet :
```python
import cv2
import pyzed.sl as sl

def main():
    print("Running...")
    init = sl.InitParameters()
    cam = sl.Camera()
    if not cam.is_opened():
        print("Opening ZED Camera...")
    status = cam.open(init)
    if status != sl.ERROR_CODE.SUCCESS:
        print(repr(status))
        exit()

    runtime = sl.RuntimeParameters()
    mat = sl.Mat()

    key = ''
    while key != 113:  # for 'q' key
        err = cam.grab(runtime)
        if err == sl.ERROR_CODE.SUCCESS:
            cam.retrieve_image(mat, sl.VIEW.LEFT_UNRECTIFIED)
            cv2.imshow("ZED", mat.get_data())
            key = cv2.waitKey(5)
        else:
            key = cv2.waitKey(5)
    cv2.destroyAllWindows()

    cam.close()
    print("\nFINISH")


if __name__ == "__main__":
    main()
```
