### ISSUE TITLE
Can I use ZED1 to detect objects such as people or cars?

### ISSUE THREAD

**Issue by mengssui** [stereolabs/zed-examples#265]
Having buying a zed1 ,but it said objects detection only for the zed 2. 
Is there any way to use zed1 to detect objects?

**Comment by obraun-sl** [comment]
Not with the ZED SDK, but you can check the YOLO integration here : 
https://github.com/stereolabs/zed-yolo

**Comment by mengssui** [comment]
> Not with the ZED SDK, but you can check the YOLO integration here :
> https://github.com/stereolabs/zed-yolo

Thanks you！ I am going to have a try.
