### ISSUE TITLE
streaming Python code 

### ISSUE THREAD

**Issue by arun-ravindran** [stereolabs/zed-examples#267]
The streaming Python zed-examples did not work for me  (open failed) as given (Zed SDK 3.1). I had to make the following modifications to get it to work -
streaming_receiver.py 
Changed init.set_from_stream(ip) to init.set_from_stream(ip, port)
streaming_sender.py
Added stream.port = port

Thanks!

**Comment by BingXiong1995** [comment]
If you didn't specify which port you are going to use, the default port is 30000
