### ISSUE TITLE
Body Tracking: Visualization of different poses

### ISSUE THREAD

**Issue by aozcan97** [stereolabs/zed-examples#269]
I'm trying to find a way with the source code for C++ how to evaluate the position of the arms and legs and output it in the visualization window (GLViewer). My goal is to detect poses like the arms are up or down. @nesnes @adujardin @obraun-sl @P-yver

**Comment by obraun-sl** [comment]
I think that what you want is done in the sample Body Tracking : 
https://github.com/stereolabs/zed-examples/tree/master/body%20tracking/cpp
It shows the bones in the OpenGL window (in 3D)

**Comment by aozcan97** [comment]
You are right the skeleton is displayed correctly, but I still want recognition and an output that the arms are in the air or not. As well as the ID and the speed which is above the head of the person.

**Comment by aozcan97** [comment]
I found these links on the Stereolabs website, but they don't really show anything about the position of the joints or the position of the links of the body parts. @obraun-sl 
https://www.stereolabs.com/docs/api/group__Object__group.html#gacce1373b1af32c33563d484bf326bc8e

https://www.stereolabs.com/docs/api/group__Object__group.html#ga87fd98be8a135ca065216e49ff6e4fdf

**Comment by obraun-sl** [comment]
Hi. Here is a picture for the Body18 keypoints 
![SDKBodyTrackingKP18](https://user-images.githubusercontent.com/14200362/89878768-a832ce00-dbca-11ea-9521-45ccb494f365.jpg)
