### ISSUE TITLE
How to obtain the origin of an loaded .area file

### ISSUE THREAD

**Issue by HyperLethalVector** [stereolabs/zed-examples#271]
Hi there!

From what I understand, once a ZED camera is localized using a .area file that's been loaded, we should be able to synchronize the positions of multiple ZED cameras in a scene.

however, how do we obtain the origin/world coordinate frame which describes the center of the .area file?

I've looked over the documentation, and examples but couldn't find anything. In theory this should be possible, but I can't find how this is done.

Could you shed some light on this subject?

Thanks.

**Comment by obraun-sl** [comment]
Hi,
The origin of the area file is the same as the positional tracking. If you don't specify a initial transform in enablePositionalTracking() then it's the position of the camera at the very first frame (0,0,0).
