### ISSUE TITLE
high frequency imu data from .SVO

### ISSUE THREAD

**Issue by hojunson** [stereolabs/zed-examples#273]
Is there any way to get imu data from .SVO in high frequency. 
In the API page, it seems like impossible now.

![image](https://user-images.githubusercontent.com/24233353/90327779-40330d80-df65-11ea-86f0-a516511eca25.png)

**Comment by obraun-sl** [comment]
Hi,
The SVO does not contains high frequency imu data. It only contains data synchronized to the image (quaternion)
