### ISSUE TITLE
SVO HVEC compression causing Zed Explorer to crash (Jetson Xavier NX)

### ISSUE THREAD

**Issue by Alexander5F** [stereolabs/zed-examples#274]
Recording on lossy compression works every time, but as soon as I switch to HVEC the app instantly crashes. Has anyone else had this problem?

**Comment by P-yver** [comment]
Hi @Alexander5F ,
Have you try the [latest version](https://www.stereolabs.com/developers/release/) of the ZED SDK?
Moreover, do you installed libv4l-dev' apt package on your Jetson? it is a known issue leading to this behavior.
