### ISSUE TITLE
Stream remotely over 5G network

### ISSUE THREAD

**Issue by BingXiong1995** [stereolabs/zed-examples#276]
Our team is using ZED2 on a drone to do real-time remote spatial mapping. The drone will fly far away so a local network streaming might not be available. We used a large bandwidth server(100Mbs) with a public IP and using a 5G network card on our drone to establish a remote network transmission. We have tried a lot of method such as port forwarding and VPN to get the streaming from the drone over the network, but all of them are failed. Is there any suggestion to get stream over a server with public IP ?
@obraun-sl  Thanks for your reply!

**Comment by obraun-sl** [comment]
If you are using the streaming module from the ZED SDK, you need to make sure that the sender and receiver are on the same network. 
Otherwise, you might be interested in our new gstreamer plugin here : 
https://github.com/stereolabs/zed-gstreamer

**Comment by BingXiong1995** [comment]
@obraun-sl We'll try that later. Thanks for your amazing stereo camera!

**Comment by Vertigo-VR** [comment]
Hello.

Any update to using ZED for remote spatial mapping? Our use case is much alike yours @BingXiong1995, did you come up with any good solutions? Thanks.

**Comment by keli95566** [comment]
Hi @BingXiong1995 , I am wondering if you have tried the Gstreamer option and is able to retrieve the images from Unity correctly? Thank you!
