### ISSUE TITLE
[ZED]INFO: Sensors not detected

### ISSUE THREAD

**Issue by yesming** [stereolabs/zed-examples#285]
![zed issue](https://user-images.githubusercontent.com/19283778/93079571-57474700-f65a-11ea-8d0d-95f64e9b0594.png)

What does '[ZED]INFO: Sensors not detected' mean?
Is the inner sensor such as IMU etc. broken?
I'm using ZED 2 stereo camera..

Please tell me the solution what can deal with it
Object detection API doesn't work...

**Comment by obraun-sl** [comment]
Can you type lsusb and check that it has 2b03:F781 as output (that's the sensor MCU) ?

**Comment by sAgmin** [comment]
> Can you type lsusb and check that it has 2b03:F781 as output (that's the sensor MCU) ?

It is fixed automatically..... I don't know why
I suspect that the camera has been used for a long time (3hr? or more?).
