### ISSUE TITLE
spatial mapping very large area (point cloud)

### ISSUE THREAD

**Issue by Branch-h** [stereolabs/zed-examples#290]
Hi,
I would like to know how big area I can map with spatial mapping (point cloud) using Jetson Nano and ZED-mini? To what factors I am limited? Also, I would like to ask what parameters I should set to get better results (bigger map) and any other advice? I was testing with examples and ZEDfu but I don't understand precisely how that spatial mapping with point cloud works and I would like to know more...
Thanks!
![max_spatial_mapping_memory_reached](https://user-images.githubusercontent.com/67629250/94345441-0f46fd80-0026-11eb-89bb-9079504469ea.jpg)

**Comment by P-yver** [comment]
Hi,
Have you take a look at our [documentation page](https://www.stereolabs.com/docs/spatial-mapping/using-mapping/)?
To have better results for large area, consider to use a [low resolution ](https://www.stereolabs.com/docs/api/structsl_1_1SpatialMappingParameters.html#a25bef5bd7d6f0c201bccdc73bb6680fa).

Spatial Mapping with point cloud follow the same behavior as for Mesh, only the type of results is different, just points, no surfaces defined by triangles.
