### ISSUE TITLE
Example Code for ZED2 Marketing Video

### ISSUE THREAD

**Issue by JosephRedfern** [stereolabs/zed-examples#294]
Hello,

Would Stereolabs be able to share the code (or similar code) used to generate the video seen here: https://www.stereolabs.com/zed-2/ (i.e. overlaying trajectory, labels and speeds for detected objects, with a moving camera)? I'm finding dealing with the different coordinate systems fairly tricky and some further examples would be very useful for my work.

Thank you.

**Comment by obraun-sl** [comment]
Hi,
You can try this repo here : 
https://github.com/obraun-sl/zed-object-detection-viewer

**Comment by JosephRedfern** [comment]
This looks perfect. Thank you so much, @obraun-sl !
