### ISSUE TITLE
How to calculate heading angle from magnetometer?

### ISSUE THREAD

**Issue by PonyPC** [stereolabs/zed-examples#295]
I get the magnetic field data through: magnetic_field = sensors_data.get_magnetometer_data().get_magnetic_field_uncalibrated()
But it seems to be a little different from android magnetic sensor data.
What does x, y, z mean? How to calculate the heading angle from: arctan(y/x)
Thanks.

**Comment by leequan** [comment]
Hi,@PonyPC
Do you calculate this x, y, Z angle？

**Comment by PonyPC** [comment]
@leequan  Sorry I didn't get you.
