### ISSUE TITLE
IMU coordinate

### ISSUE THREAD

**Issue by 478161648** [stereolabs/zed-examples#296]
Is the IMU coordinate system left-handed or right-handed?
at this link： https://www.stereolabs.com/docs/sensors/   . It looks like the green axis is right-handed and the red axis is left-handed.

**Comment by obraun-sl** [comment]
The IMU quaternion is given in the coordinate system provided through the initParameters::coordinate_system. There are multiple system available that can be left or right handed
https://www.stereolabs.com/docs/api/group__Core__group.html#ga1114207cbac18c1c0e4f77a6b36a8cb2
