### ISSUE TITLE
Body Tracking for python API

### ISSUE THREAD

**Issue by niemiaszek** [stereolabs/zed-examples#297]
Body Tracking sample is present only in c++ API, and there is good description of it in [ObjectDetection module page in c++ docs](https://www.stereolabs.com/docs/api/group__Object__group.html). I could also find some reference to keypoints in [python api docs](https://www.stereolabs.com/docs/api/python/classpyzed_1_1sl_1_1ObjectData.html#a303c74b35dd67274ac7f7c18f1813494), but there is no sample included in this repo. Is python API support for body tracking in development (out probably in next patch, when?) or will it remain as c++ exclusive? Can I use body tracking with 3D keypoints using python API now?

**Comment by P-yver** [comment]
The python sample is on the way !
Stay tune for the next release.
