### ISSUE TITLE
Extracting large svo files (25GB)  get stuck halfway

### ISSUE THREAD

**Issue by alankongfq** [stereolabs/zed-examples#298]
I am extracting a large svo files which has about 600k frames inside at 1280 x 720.
I used the code provided in [here](https://github.com/stereolabs/zed-examples/tree/master/svo%20recording/export/python) and was able to extract 50% of the svo content. After 50%, the progress got stuck and I do not know what is the reason and kind of stuck. Any suggestions to debug this? I do not think there is a limitation in my storage space or the file codec format so the issue should be something else.

**Comment by adujardin** [comment]
You should try to display the code returned by the [grab function](https://github.com/stereolabs/zed-examples/blob/master/svo%20recording/export/python/export_svo.py#L138).
You can print the number of the frame in the SVO and where it is currently and enable the [verbose mode](https://www.stereolabs.com/docs/api/python/classpyzed_1_1sl_1_1InitParameters.html#a5e7a148739a4d13b5cd266e779136a31) in the init parameters to see if there are any messages.
