### ISSUE TITLE
What is the unit of the EXPOSURE?

### ISSUE THREAD

**Issue by HanjieLuo** [stereolabs/zed-examples#30]
I want to control the exact exposure time by setting the sl::zed::ZED_EXPOSURE value (SDK v1.1) while the file says that:

**ZED_EXPOSURE: Defines the exposure control. A -1 value enable the AutoExposure/AutoGain control. Affected value should be between 0 and 100 for manual control. A 0 value only disable auto mode without modifing the last auto values, while a 1 to 100 value disable auto mode and set
exposure to chosen value**

What is the unit of the this value?

THX!

**Comment by WASCHMASCHINE** [comment]
Stereolabs support: "The exposure setting isn't related to real world values so I can't give you a measure in time unit." But this was a newer SDK.
