### ISSUE TITLE
ZED Depth Viewer "Texture 90" option function?

### ISSUE THREAD

**Issue by 4nightmare** [stereolabs/zed-examples#302]
Hi,

I don't know where to write so I posted here... Hope to not have done a mistake

I'm extracting point cloud after a recording session and I was wondering what is the function of "Texture 90" option in the ZED Depth Viewer? I'm new to coding so I'm using for the moment the Depth Viewer software for extracting point cloud of some frames.

I've noticed that using this "texture 90" function, the resulting Point cloud is smaller but the main differences in number of point are in the background... is this a kind of depth filter? Could you explain me what is the function / how does it work this option?
Does it improve or reduce in some ways the point cloud quality?

I've read from docs about "confidence" that is referred to depth confidence and I will keep it at 50% as standard value, but I'm not sure If activate or not the Texture 90 option.

Thank you in advance

![image](https://user-images.githubusercontent.com/58037826/97420559-bf50a480-190b-11eb-8029-7d897a19a1df.png)

![image](https://user-images.githubusercontent.com/58037826/97420618-d2fc0b00-190b-11eb-8020-7c0aa07714f3.png)

**Comment by P-yver** [comment]
This checkbox is simply a preset (to 90) of the slider `Texture Confidence` which you can find in the Settings Panel of the Depth Viewer. _Confidence 50_ is another preset for `Confidence `filtering.

`Texture confidence` removes depth datas from uniform areas of the image (here, the sky which is almost a flat blue area).
`Confidence` removes depth data on objects edges.

They are both designed to firstly remove erroneous points.
