### ISSUE TITLE
Spatial mapping memory error

### ISSUE THREAD

**Issue by hojunson** [stereolabs/zed-examples#304]
I would like to make a point cloud map by using Zed2. 
I tested both operating system(Windows 10 and Ubuntu 18.04) 
I recorded SVO files and tried to make the map through ZEDfu and python codes. 

ZEDfu showed "maximum spatial memory error(?)", not accurate because it was shutdown to catch it. 

Using python code, all the status of frames for the mapping returned "OK" but the result of ".obj" didn't have all the frames. 
It looked like the mapping was failed in the middle of process. 

The SVO files have > 3000 frames with full resolution(2K)

Any suggestions?

**Comment by P-yver** [comment]
The ZEDfu issue, as well as the Python issue, have been added to our roadmap and should be fixed in the future 3.3.1 release. Meanwhile, you can try the [C++ example](https://github.com/stereolabs/zed-examples/tree/master/spatial%20mapping/basic/cpp) which should be running as expected.
