### ISSUE TITLE
Computer shader on GPU Image

### ISSUE THREAD

**Issue by AndreAhmed** [stereolabs/zed-examples#306]
Hi,
in the documentation there is an ability  to allocate ZedMat on The GPU, and retrieve the image on that Zed Mat. I'm using C# and Unity3D and planning to do some computer shader on that matrix. How would I refer to zed mat to the compute shader, because I assume both are on the GPU ?

**Comment by obraun-sl** [comment]
Hi,
If you are using Unity/C#, best is to look at the dedicated repository here : 
https://github.com/stereolabs/zed-unity
or for the C# : 
https://github.com/stereolabs/zed-csharp-api

With the Unity plugin, you can have direct access to the images as Texture2D , compatible with computeShader inputs (see textureEye in ZEDRenderingPlane.cs)
