### ISSUE TITLE
get point3D and save as .pcd  issue

### ISSUE THREAD

**Issue by adetails** [stereolabs/zed-examples#309]
ZED 2 
Python3.7
If i'd like to take out a part of a image and it's corresponding pointclouds.how can i do it?as i known, i can use read_svo.py(SVO playback) or just use the ZED Depth Viewer.but i have the two questions.
1.when i use SVO recording/playback,i want to save a image and it's corresponding point_cloud which the point_cloud would be saved in a PCD file.how can i do it?
2.if i use ZED_Depth Viewer .I do can get a image and it's corresponding point_cloud.
I'm stuck in a quagmire,please help me
Thanks

**Comment by adetails** [comment]
![image](https://user-images.githubusercontent.com/57819755/99641289-07836280-2a85-11eb-886c-6caad09baa38.png)
if i want to save the point_cloud in PCD as the same as the format the ZED Depth Viewer does.how can i do it

**Comment by P-yver** [comment]
Hi,
The Python API let you save retreived data in different file format:
https://www.stereolabs.com/docs/api/python/classpyzed_1_1sl_1_1Mat.html#ae0568cd94ee09fa51eaf50679e3a2def

You can save images in jpg/png as well as Point Cloud in PCD/PLY
