### ISSUE TITLE
focal length in mm

### ISSUE THREAD

**Issue by nikky4D** [stereolabs/zed-examples#31]
Hi,

I need to convert the focal length, fx/fy, from pixels to mm. Can someone help me with this?

I believe the formula is something like this:
focal_in_pixels = (focal_in_mm / sensor_width_in_mm) * image_width_in_pixels

Is this correct to make this conversion? What are the values for sensor_width? The image width is just resolution_width or resolution_width/2? Any help is appreciated.

**Comment by adujardin** [comment]
Hi,
This https://github.com/stereolabs/zed-opencv/issues/39 should provide the information you need
