### ISSUE TITLE
Measure xyz positions from depth image

### ISSUE THREAD

**Issue by Zumbalamambo** [stereolabs/zed-examples#314]
I have exported the depth images through ZEDFu. How do I find the `[xyz]` values of each pixel from the same? [This](https://github.com/stereolabs/zed-examples/blob/ee3ef19886e0ad2573648e87c0fe49ce03b56009/tutorials/tutorial%203%20-%20depth%20sensing/python/depth_sensing.py#L74)  gives the depth. However, how do I also get the `x,y` values from the origin?

**Comment by P-yver** [comment]
Hi,
I am not sure to really understand your question, ZEDfu exports Meshes in OBJ format, no depth.

In the given sample ` point_cloud_value` contains the [X;Y;Z;RGBA] value of the image' center pixel.
The `Z` is the depth (from the camera to the object).
