### ISSUE TITLE
Dynamic camera gain adjustment as a function of daylight intensity

### ISSUE THREAD

**Issue by Tetsujinfr** [stereolabs/zed-examples#321]
hi, my ZED mini is quite sensitive to sun light variation, like any camera I guess. On days with light intensity volatility, for instance due to sparse cloud coverage, the SLAM algo get lost as soon as a cloud hides the sun or unhides it.
I guess I understand the limitations here but, I was wondering, why not having considered adding a light sensor as part of the set of sensor and try to dynamically adjust the gain of the camera when the ambient light varies a lot?
Is it something that could work you think?
Am I the only one using the ZED outdoor and facing those challenges?

thanks

**Comment by obraun-sl** [comment]
Are you using AutoExposure mode or Manual mode ? Because the Auto exposure should compensate variations of the light (if not too big)
