### ISSUE TITLE
spatial mapping result was very bad

### ISSUE THREAD

**Issue by hudmgy** [stereolabs/zed-examples#322]
hi, 
I used the tool ZEDfu to get a spatial mapping of a room, but the results were terrible. There are a lot of holes and disconnections in it. 
My stereo camera is ZED2, and SDK version is 3.3.3. 
Did I do something wrong？

**Comment by obraun-sl** [comment]
Hi,
You can try to record a SVO file (with ZED Explorer) and then process it in ZEDFu to see if you have differences. If yes, then maybe the compute power of your PC is not enough to handle live mapping properly.

**Comment by hudmgy** [comment]
> Hi,
> You can try to record a SVO file (with ZED Explorer) and then process it in ZEDFu to see if you have differences. If yes, then maybe the compute power of your PC is not enough to handle live mapping properly.

Hi
Thank you for reply！The result is better when using SVO file as input.
My computer is Jetson Xavier NX,  is it not enough?
What types of computer do you recommend?

thank you

**Comment by obraun-sl** [comment]
Xavier AGX will give better performances, even if Xavier NX should be enough. Make sure you are in max performance mode (MAXN).

**Comment by Tetsujinfr** [comment]
I have pretty good results on NX, fyi.
What resolution did you run SLAM on? Are you sure GPU is used?
