### ISSUE TITLE
where can i find this method: setDepthMaxRangeValue

### ISSUE THREAD

**Issue by dibet** [stereolabs/zed-examples#324]
Hi, i am searching into the file Camera.hpp and i can not find this method: "setDepthMaxRangeValue".
Where is it defined?
Thanks

**Comment by P-yver** [comment]
Hi, it has been removed from the 3.X API: look at [this file ](https://www.stereolabs.com/developers/release/3.0/migration-guide/) to update your code.

It is now in `InitParameters::depth_maximum_distance`
