### ISSUE TITLE
Failed reload a exist FusedPointCloud file

### ISSUE THREAD

**Issue by C-002** [stereolabs/zed-examples#325]
I'm trying to create a reloclization app which combines Positional Tracking and Spatial Mapping in the samples. But there are some problems occurred when loading a exist obj file which created by sample program, hope you can help.

I worked on SpatialMapping sample code as a starting point. The basic sample of compiles and runs smoothly. I chose to use Fused Point Cloud. The final saved obj file can be clearly viewed in Meshlab.  

However, when I hope to use the `load()` function of the FusedPointCloud module to load the generated obj file and restore the historical point cloud, an error message is printed on the terminal:
`[ZED][MESH] [ERROR] Missing mtl file or texture file.`
It seems that Mesh-related files are missing and the return of `load()` is false.

I read the API Reference, which mentioned that the `load` function only needs to enter the path of the file, and I cannot modify anything. And the type parameter in `save` used by Mesh or FusedPointCloud is `MESH_FILE_FORMAT::OBJ` by default. I tried to use `PLY` instead, but the same error occurred.

I don't know if I have any mistakes in understanding or using the functions of saving and loading maps, as a beginner of ZED camera. Thanks for any suggestions.

**Comment by P-yver** [comment]
Indeed there is actually an issue when reloading a FusedPointCloud saved as OBJ, until the SDK will be fixed you can save your FusedPointCloud as a PLY using sl::FusedPointCloud::save("MyFusedPC", sl::MESH_FILE_FORMAT::PLY);

PS: you can not convert sl::Mesh to sl::FusedPointCloud by save/load and vice-versa.
