### ISSUE TITLE
Issue when reading svo file Jetson Nano

### ISSUE THREAD

**Issue by jhastoy** [stereolabs/zed-examples#328]
Hello !
I have an issue when I try to playback a SVO file recorded on Jetson Nano. In fact my code run well on my Desktop but on my jetson nano with JetPack 4.4, the while loop reading each frame of the svo is infinite because the error ERROR_CODE.END_OF_SVOFILE_REACHED is never returned by zed.grab() with the same svo file of 10 frames.
When I print the read frame position with get_svo_position(), results are very strange like : 1 then 2 then 0 then 1 then 3 then... that doesn't happen on my Linux Desktop. 

      
```
        input_type = sl.InputType()
        input_type.set_from_svo_file(input_path)

        init_params = sl.InitParameters(input_t=input_type)

        init_params.camera_resolution = self.init_params.camera_resolution
        init_params.camera_fps = self.init_params.camera_fps
        init_params.depth_mode = self.init_params.depth_mode
        init_params.coordinate_units = self.init_params.coordinate_units



        err = self.zed.open(init_params)
        if err != sl.ERROR_CODE.SUCCESS:
            raise Exception(err)

        print(self.zed.get_svo_number_of_frames()) # return 10
        while err != sl.ERROR_CODE.END_OF_SVOFILE_REACHED:
            err = self.zed.grab()
            print(err)
            if err == sl.ERROR_CODE.SUCCESS:
                self.zed.retrieve_image(image, sl.VIEW.LEFT)
```

I've already reinstalled the ZED SDK 3.3.3 and updated the zed python api.
Thanks for you help !

**Comment by laszloturanyi** [comment]
Is there any solution for this problem?
