### ISSUE TITLE
ZED not opening: cudaErrorInvalidValue

### ISSUE THREAD

**Issue by ajdroid** [stereolabs/zed-examples#33]
I ran the ZED Depth Viewer and got a `cudaErrorInvalidValue` and subsequently a segmentation fault.

My system is Ubuntu 16.04, Cuda 8, GPU is Nvidia GTX 1080Ti. 

The SDK version is 2.2-RC4. 

I also have to use `sudo` with `guvcview -d /dev/video0 -x 2560x720 -i 30` to get access to the camera. Is it possible to do this without it?

**Comment by adujardin** [comment]
Hi,
Since you're using an RC SDK, could you contact the support for this issue please (support@stereolabs.com) ?
