### ISSUE TITLE
Higher framerate with grayscale mode?

### ISSUE THREAD

**Issue by Tetsujinfr** [stereolabs/zed-examples#332]
Hi

Is it possible now or in the future to have access to higher framerate in 2k or 1080p resolution, with 8bits grascale or even binary color scheme?
Assuming the limitation is the USB bandwith and not the sensor data processing on the camera.
Would be very useful for some cv algos, just a though.
Thanks

**Comment by Myzhar** [comment]
Cross-post. You can find a reply on the Stereolabs forum:
https://community.stereolabs.com/t/grayscale-only-frames-and-higher-framerate/94/2
