### ISSUE TITLE
Depth FILL mode does not work for SDK versions after v3.0.3 (with Jetpack 4.3 + Cuda10.0) Please Fix!!!

### ISSUE THREAD

**Issue by solimov-advanced** [stereolabs/zed-examples#339]
Depth FILL mode does not work for SDK versions after v3.0.3 (with Jetpack 4.3 + Cuda10.0).

There has already been 4 new versions since... what's going on???

**Comment by P-yver** [comment]
The [new 4.3.1](https://www.stereolabs.com/developers/release/) should fix your issue.
