### ISSUE TITLE
ModuleNotFoundError: No module named 'ogl_viewer'

### ISSUE THREAD

**Issue by AdeQQ** [stereolabs/zed-examples#342]
Hi! 
When I'm trying to run the python object detection example in vs code I get the following:
`Traceback (most recent call last):
  File "e:\zed_python_object_detection.py", line 26, in <module>
    import ogl_viewer.viewer as gl
ModuleNotFoundError: No module named 'ogl_viewer'`.
I have all the packages installed and up to date. Anybody had such an issue?

**Comment by accolypse1994** [comment]
Hey I have the same issue. Were you able to solve it ?

**Comment by qt-truong** [comment]
Hi @accolypse1994,

You can check https://github.com/stereolabs/zed-examples/issues/319#issuecomment-765250638 which could be related to your problem

**Comment by cgsuccesscg** [comment]
Hey I have the same issue. Were you able to solve it ?
