### ISSUE TITLE
VS2015 LINK ERROR

### ISSUE THREAD

**Issue by MF1523017** [stereolabs/zed-examples#35]
hi, I am trying to test the example code(hello ZED) ,but  I get a link error after generating the project,
my environment is windows 10, VS2015,  here is the error:
> main.obj : error LNK2019: Unresolved external symbols "public: __thiscall sl::String::String(void)" (??0String@sl@@QAE@XZ)，The symbol is referenced in the function _main

**Comment by obraun-sl** [comment]
Hi,
Are you using cmake to generate your VS project? It seems that your project does not link against sl_core64.lib (which contains sl::String definition)

**Comment by MF1523017** [comment]
Thank you for your reply, I have solved it！
