### ISSUE TITLE
AttributeError: 'pyzed.sl.ObjectDetectionRuntimeParameters' object has no attribute 'object_class_filte'

### ISSUE THREAD

**Issue by john-lihn** [stereolabs/zed-examples#352]
@P-yver  I ran the example https://github.com/stereolabs/zed-examples/tree/master/tutorials/tutorial%206%20-%20object%20detection/python

error occurred AttributeError: 'pyzed.sl.ObjectDetectionRuntimeParameters' object has no attribute 'object_class_filte' 
How to solve it?

**Comment by john-lihn** [comment]
> @P-yver I ran the example https://github.com/stereolabs/zed-examples/tree/master/tutorials/tutorial%206%20-%20object%20detection/python

![image](https://user-images.githubusercontent.com/52641610/110766690-65d08d00-8290-11eb-8d1f-1bc26e7e8e8a.png)

> 
> error occurred AttributeError: 'pyzed.sl.ObjectDetectionRuntimeParameters' object has no attribute 'object_class_filte'
> How to solve it?

**Comment by john-lihn** [comment]
> > @P-yver I ran the example https://github.com/stereolabs/zed-examples/tree/master/tutorials/tutorial%206%20-%20object%20detection/python
> 
> > error occurred AttributeError: 'pyzed.sl.ObjectDetectionRuntimeParameters' object has no attribute 'object_class_filte'
> > How to solve it?
>
>zed version
![image](https://user-images.githubusercontent.com/52641610/110766950-af20dc80-8290-11eb-9684-4e2397072eb6.png)

**Comment by qt-truong** [comment]
Hi @john-lihn,

You are using the ZED SDK 3.2, and the `object_class_filter` attribute has been added to the Python API in ZED SDK 3.4.
You can download a more recent version of the SDK here : https://www.stereolabs.com/developers/release/

**Comment by john-lihn** [comment]
Okay thank you, I will try it out, thank you

**Comment by john-lihn** [comment]
Will you use the tensorflow h5 model or the pytorch model to perform the object detection function in the future, so that more experiments can be carried out in the future?

**Comment by john-lihn** [comment]
![image](https://user-images.githubusercontent.com/52641610/110780087-442ad200-829f-11eb-8ab7-96282583c32d.png)
Sorry to interrupt again, I have updated the latest version of python API, but this error still exists, how can I improve it?thank you

**Comment by john-lihn** [comment]
![image](https://user-images.githubusercontent.com/52641610/110785831-5b20f280-82a6-11eb-8c81-04c220ab200f.png)
Sorry to interrupt again, I have updated the latest version of python API, but this error still exists, how can I improve it, thank you

**Comment by qt-truong** [comment]
There is a typo in your code : the attibute is "object_class_file**r**"

**Comment by john-lihn** [comment]
Thank you very much for your help, it is ready to run now, thank you again
