### ISSUE TITLE
Body Tracking Example Code doesnt work

### ISSUE THREAD

**Issue by accolypse1994** [stereolabs/zed-examples#353]
Hello,
The example code is working on my friend computer however the same code is not working in my computer. I am using PyCharm Community Edition 2020.2 and python 3.6. I got error viewer part of the code and it says "line 490, in init
    glutCreateWindow("ZED Body Tracking"). The image of the error has been attached. Could you help me please ? 
![resim_2021-03-11_150447](https://user-images.githubusercontent.com/60695165/110799123-1e8bd180-827b-11eb-9283-1e34e3db272c.png)
"

**Comment by qt-truong** [comment]
Hello,

Can you try changing the call to `glutCreateWindow("ZED Body Tracking")` to `glutCreateWindow(b"ZED Body Tracking")` and see if that fixes your problem ?
It seems that there are issues on how strings are encoded as suggested here : https://stackoverflow.com/questions/27093037/python-glutcreatewindow-error-wrong-type

**Comment by accolypse1994** [comment]
Thank you so much. It works after this.
