### ISSUE TITLE
Object detection problem

### ISSUE THREAD

**Issue by john-lihn** [stereolabs/zed-examples#356]
HI, when I was testing object detection and thinking about its application recently, I found that he did very good 3D sampling, but when he detected an angle, he divided the part of my hand into another person’s object.
![image](https://user-images.githubusercontent.com/52641610/111122964-bb1ae000-85a9-11eb-93f1-55c92159efb8.png)

**Comment by P-yver** [comment]
Hi,
It looks like a miss detection from the AI model, try to increase the `sl::ObjectDetectionRuntimeParameters::detection_confidence_threshold` to discard this kind of false detection.
