### ISSUE TITLE
ZED SDK Download down

### ISSUE THREAD

**Issue by matteorr** [stereolabs/zed-examples#36]
I am trying to download the Cuda 9 SDK version 2.2 for Linux from https://www.stereolabs.com/developers/release/2.2/#sdkdownloads_anchor, but get redirected to https://www.stereolabs.com/.

This was not happening a couple days ago when I downloaded the SDK for Cuda 8, and seems to be happening for all SDK versions and platforms.

**Comment by adujardin** [comment]
Thanks for the report, the issue is now fixed
