### ISSUE TITLE
Object trajectory tracking problem

### ISSUE THREAD

**Issue by john-lihn** [stereolabs/zed-examples#360]
Hello, when I read your teaching document, I was very interested in the tracking trajectory in your object tracking, so I tried to use 3D object detection to complete this case, because I am using OpenGL to code for the first time, so I want to Inquiry, Hello, our text box. When I read your teaching document, I was very interested in the tracking trajectory in your object tracking, so I tried to complete this case with 3D object detection. I want to improve this The operation of the object, but I check your software package, there is no example of the program, I don’t know how to run them
My code is in [this](https://gitlab.com/lihn881216/zed-positional-tracking.git)

**Comment by Myzhar** [comment]
`Positional tracking` and `Object Tracking` are two different features of the ZED SDK.
Positional tracking: localization of the camera in the space
Object Tracking: localization of a detected object in the space. This is a feature of the [Object Detection module](https://github.com/stereolabs/zed-examples/tree/master/object%20detection)
