### ISSUE TITLE
streaming failed. [UDP] Multicast group join failed (setsockopt()) 

### ISSUE THREAD

**Issue by reginalluna** [stereolabs/zed-examples#361]
### sender device info:

1. System: Windows 10
2. GPU:  GTX1070
3. CUDA: 11.1
4. ZED SDK: 3.4.2
5. OpenCV (yes)

### receiver device info:
1. System: Ubuntu18.04
2. GPU: GTX750M
3. CUDA: 10.0
4. OpenCV (yes)

---
When I tried to run `python streaming_sender.py`, it shows 
![image](https://user-images.githubusercontent.com/54960230/113444086-30b3e800-93c1-11eb-8f0b-63e7c2b5f4c3.png)

And, I ran `./ZED_Streaming_`, it said:
`
`

**Comment by reginalluna** [comment]
> ### sender device info:
> 
>     1. System: Windows 10
> 
>     2. GPU:  GTX1070
> 
>     3. CUDA: 11.1
> 
>     4. ZED SDK: 3.4.2
> 
>     5. OpenCV (yes)
> 
> 
> ### receiver device info:
> 
>     1. System: Ubuntu18.04
> 
>     2. GPU: GTX750M
> 
>     3. CUDA: 10.0
> 
>     4. OpenCV (yes)
> 
> 
> When I tried to run `python streaming_sender.py`, it shows
> ![image](https://user-images.githubusercontent.com/54960230/113444086-30b3e800-93c1-11eb-8f0b-63e7c2b5f4c3.png)
> 
> And, I ran `./ZED_Streaming_`, it said:
> `Opening the stream requires the IP of the sender
Usage : ./ZED_Streaming_Receiver IP:[port]
You can specify it now, then press ENTER, 'IP:[port]': 224.0.0.0:30000
[ZED][Streaming] Error: Stream opening timeout
[Sample][Error] Camera Open  | FAILURE : The function does not perform as expected. Exit program.
 `

**Comment by obraun-sl** [comment]
The IP adress you enter does not seem to be correct as it lloks like a multicast adress.
You need to enter the IP adress of the sender (the streaming is based on RTP unicast). 
To get the IP of the sender, type ipconfig on your windows PC, and you should get a IPv4 adress under the form 192.168.X.X

**Comment by reginalluna** [comment]
> The IP adress you enter does not seem to be correct as it lloks like a multicast adress.
> You need to enter the IP adress of the sender (the streaming is based on RTP unicast).
> To get the IP of the sender, type ipconfig on your windows PC, and you should get a IPv4 adress under the form 192.168.X.X

Oh, let me try it again. Thank you. And, there's a weird problem that happened to my PC. The ZED camera has no reaction (not working) toward the USB3.0 ports of the PC after I unplugged it from my PC to my Ubuntu laptop and replugged it back to the PC.

**Comment by reginalluna** [comment]
> ipconfig

Hi, while I ran `ipconfig`, I got 
![image](https://user-images.githubusercontent.com/54960230/113483066-9b236180-946f-11eb-8b6d-65f969616c19.png)

Then, I ran `./ZED_Streaming_Receiver 192.168.0.20: 30000` on Ubuntu, and it still gets `[ZED][Streaming] Error: Stream opening timeout [Sample][Error] Camera Open | FAILURE : The function does not perform as expected. Exit program.`

**Comment by obraun-sl** [comment]
Can you try on the same ubuntu PC? ie : 
./ZED_Streaming_sender
./ZED_Streaming_receiver localhost

to check first that it's working. 
On windows, once an application communicates on the network, you must make sure that comms are authorized for the app (you should have a popup window that ask if you want this app to access the network).

**Comment by reginalluna** [comment]
> Can you try on the same ubuntu PC? ie :
> ./ZED_Streaming_sender
> ./ZED_Streaming_receiver localhost
> 
> to check first that it's working.
> On windows, once an application communicates on the network, you must make sure that comms are authorized for the app (you should have a popup window that ask if you want this app to access the network).

Thank you so much for the detailed explanation.

Unfortunately, it doesn't work. 
When I ran the python scripts on PC (windows10), I got:
- sender: 
![image](https://user-images.githubusercontent.com/54960230/113514254-8dd3a900-953b-11eb-894e-49b08d88699d.png)
- receiver: 
![image](https://user-images.githubusercontent.com/54960230/113514262-9a580180-953b-11eb-822d-1c07216b33c2.png)
---
When I ran the cpp scripts on PC (windows10), it ran successfully.
- sender:
![image](https://user-images.githubusercontent.com/54960230/113514358-0470a680-953c-11eb-9fc8-c055b78683ec.png)
- receiver:
![image](https://user-images.githubusercontent.com/54960230/113514385-2e29cd80-953c-11eb-949d-1349aa79513e.png)
 ----

I have a question think what the issue with the python scripts? How can I let it works? 

Another question, how can I run the sender and plug the ZED on Ubuntu18 (the laptop), and run the receiver on the PC (windows10)? I plan to get a Jetson NX later and carry it outside to capture some data, connect the Jetson device and the laptops (windows 10 or Ubuntu18) through the Wifi hotspot provided by my phone.

The last question, if I place Jetson with ZED outdoor, is it possible for Jetson to send the data to my PC placed from home (theoretically say, the Jetson device and PC will use different internet and let Jetson send the data remotely)?

I'm an artist, so I'm not really familiar with programming. If you can help with these question, I appreciate a lot!
