### ISSUE TITLE
How can I get the sensor data which is synchronized to the image frames?

### ISSUE THREAD

**Issue by KitaharaTakuya** [stereolabs/zed-examples#367]
Hi, 
The README tells that: **"The sensor data can be retrieved in two ways: synchronized or not synchronized to the image frames."**
But in the tutorials 7-sensor data, I only found the way: **"not synchronized to the image frames"**. 
So, if you know, could you tell me how can I get the sensor data which is **synchronized to the image frames** in python?
Thank u very much!!!!!!!!

**Comment by obraun-sl** [comment]
Hi,
Use zed.getSensorsData(sensors_data, TIME_REFERENCE::IMAGE) instead of  TIME_REFERENCE::CURRENT to get synchronized data.
See here : https://github.com/stereolabs/zed-examples/blob/master/positional%20tracking/cpp/src/main.cpp#L94
