### ISSUE TITLE
std::length_error while saving mesh in spatial mapping example using vs2017.5

### ISSUE THREAD

**Issue by seraphain** [stereolabs/zed-examples#37]
Hi guys, I faced an issue when studying the spatial mapping examples.

**Hardware**
Intel Core i7-4810MQ
16G RAM
GeForce GTX 765M 2GB

**Software**
Windows 10 1709
Visual Studio 2017.5
CUDA 9.0.176
CMAKE 3.10.0
PCL 1.8.1

**Result**
When executing the line `mesh.save("mesh.obj");`, the application crashed and throwed std::length_error.

**Initial Analysis**
Debug and find that `explicit vector(_CRT_GUARDOVERFLOW const size_type _Count, const _Alloc& _Al = _Alloc())` was called with `_Count` equal to 14757395255531667456 first then 0, and the application crashed.

Thank you very much for your reading and replying.

**Comment by wysk0101** [comment]
The same "std::length_error "as I faced,    WeChat:   wysk0101

**Comment by AkashPushkar** [comment]
Did anyone found a solution for this?

**Comment by rkachach** [comment]
Same error here and the same issue is causing a crash in several other examples.

**Comment by nesnes** [comment]
Hi, can you make sure that you're running in Release mode? Th issue looks like compatibility issues in the `std::vector` implementation in debug mode (your app) and release (the ZED SDK).

**Comment by rkachach** [comment]
Thanks for the quick and concise reply. I have just switch to Release mode and the issue doesn't occur any more.  👍

**Comment by Wanggcong** [comment]
> Thanks for the quick and concise reply. I have just switch to Release mode and the issue doesn't occur any more. +1

Hi, I have similar errors. Does switching to Release mode mean change the git branch to release_3.6? Thank you!
