### ISSUE TITLE
Error: when I run the object_detection_image_viewer.py in object detection folder

### ISSUE THREAD

**Issue by HystericalHilb** [stereolabs/zed-examples#374]
_**_**when I run the object_detection_image_viewer.py in object detection folder, I meet the error:**_**_
hilb@hilb:/usr/local/zed/samples/object detection/image viewer/python$ python3 object_detection_image_viewer.py 
freeglut (foo):  ERROR:  Internal error <FBConfig with necessary capabilities not found> in function fgOpenWindow

used in Ubuntu18.04
CUDA11.1
ZED SDK3.5

**Comment by agelamin** [comment]
Did you find a solution for this error? I have the same error running the custom object detection.
