### ISSUE TITLE
Issue with Body Tracking Python

### ISSUE THREAD

**Issue by La130593** [stereolabs/zed-examples#375]
Hi,

i have a problem with the body tracking example using a ZED 2 with ZED 3.5.0 SDK and Python 3.7.9.

When starting i get the following error and both windows opens. 

```
C:\Program Files (x86)\ZED SDK\samples\body tracking\python>python body_tracking.py
Running Body Tracking sample ... Press 'q' to quit

[ZED][Object Detection] Please wait while the AI model is being optimized for your graphics card
 This operation will be run only once and may take a few minutes   Done[ZED] [Object Detection] MODEL_NOT_FOUND
```

When i try the object detection example everything works fine.

What can i do ?

**Comment by Sohob** [comment]
Hey there,

I had the same exact problem. I uninstalled the ZED SDK and CUDA 11.0, and then installed CUDA 11.1 with the compatible ZED SDK version.

After that it worked like a charm.
