### ISSUE TITLE
When convert SVO to AVI, AVI file is not closed

### ISSUE THREAD

**Issue by finymark** [stereolabs/zed-examples#379]
Hello,

I am trying to convert my svo files to avi, which I recorded with svo_recording.py example code. I used the example codes, succesful video recording and playback in svo format.
The problem is, when I run the export script and start the conversion, it stopped at 99,5% all time. 
First I waited 10-20 minutes, but nothing happened. I tried with other svo video inputs, tried with SUDO for permissions test. I worked on SSD, so then i tried on internal storage. Nothing changed in the result.

Seems like the avi file is not correctly closed. VLC media player and default Linux video player crashed after launch. SMPlayer can play the converted video.

Here is what I see in the Terminal:

keplab@keplab-desktop:/media/keplab/JetsonSSD/svo/svo_export$ python3 svo_export.py svo_rec.svo new.avi 1
Opening in BLOCKING MODE 
NvMMLiteOpen : Block : BlockType = 261 
NVMEDIA: Reading vendor.tegra.display-size : status: 6 
NvMMLiteBlockCreate : Block : BlockType = 261 
libv4l2_nvvidconv (0):(802) (INFO) : Allocating (11) OUTPUT PLANE BUFFERS Layout=1
libv4l2_nvvidconv (0):(818) (INFO) : Allocating (11) CAPTURE PLANE BUFFERS Layout=0
Converting SVO... Use Ctrl-C to interrupt conversion.
[=============================-] 99.585062%

I tried the other modes too (e.g. 0=Export LEFT+RIGHT AVI, 1=Export LEFT+DEPTH_VIEW AVI).

Hardware: Jetson AGX Xavier, Zed Stereo camera
Software: JP4.4 installed on Jetson, with Zed SDK 3.4.2

Any help is appreciated! Thanks in advance.

**Comment by jmckay** [comment]
I had the same issue and just submitted a fix so that the script completes.  If you use the latest [svo_export.py](https://github.com/stereolabs/zed-examples/blob/master/svo%20recording/export/python/svo_export.py) then it shouldn't get stuck anymore.
