### ISSUE TITLE
ZED Python API Tutorial documentation has errors

### ISSUE THREAD

**Issue by mwolfe07** [stereolabs/zed-examples#381]
There are multiple spots in the tutorial documentation in Python that have errors, incorrect functions, or variables that are never created; only referenced.

Tutorial 4 - enablePositionalTracking() isn't a function. Its enable_positional_tracking()
Tutorial 7 - In "Device Informations" - There are references to cam_model as a variable, as well as info.<functions>. Neither cam_model, nor info are referenced in the documentation.
Tutorial 7 - Function TimestampHandler() isn't referenced anywhere prior.

**Comment by qt-truong** [comment]
Hi @mwolfe07,

- You are right, there is indeed a typo in Tutorial 4 - README. Thanks for reporting, it will be fixed. However if you look into the [python script](https://github.com/stereolabs/zed-examples/blob/master/tutorials/tutorial%204%20-%20positional%20tracking/python/positional_tracking.py#L42) itself, the correct function is called and you will be able to run the tutorial
- Similarly, every README in the tutorial repository is just going through the code written in the tutorial script. You can check [sensor_data.py](https://github.com/stereolabs/zed-examples/blob/master/tutorials/tutorial%207%20-%20sensor%20data/python/sensor_data.py) for references to [cam_model](https://github.com/stereolabs/zed-examples/blob/21177250cfd96a735645dc12527fcb7daf41f5fa/tutorials/tutorial%207%20-%20sensor%20data/python/sensor_data.py#L86), [info](https://github.com/stereolabs/zed-examples/blob/21177250cfd96a735645dc12527fcb7daf41f5fa/tutorials/tutorial%207%20-%20sensor%20data/python/sensor_data.py#L84), and [TimestampHandler class](https://github.com/stereolabs/zed-examples/blob/21177250cfd96a735645dc12527fcb7daf41f5fa/tutorials/tutorial%207%20-%20sensor%20data/python/sensor_data.py#L28)

Sorry if that was unclear for you. Hope it helps !
