### ISSUE TITLE
zed.enable_object_detection(obj_param) crashes kernel

### ISSUE THREAD

**Issue by mwolfe07** [stereolabs/zed-examples#382]
I'm trying to go through tutorial 6, and just enable object detection as written in the tutorial python api docs. And it crashes my kernel. I'm using an Nvidia RTX 3090, and this is the only thing I'm doing w/ the graphics card at the moment.

**Comment by LeoReubelt** [comment]
I have a similar problem.  It logs the following...

[ZED][Object Detection] Please wait while the AI model is being optimized for your graphics card
 This operation will be run only once and may take a few minutes 

But never hits the line after 'err = zed.enable_object_detection(obj_param)'.

**Comment by icsl-Jeon** [comment]
Me also... In my case, gpu = rtx 3070
