### ISSUE TITLE
How to upgrade the firmware？What is the latest firmware version？

### ISSUE THREAD

**Issue by YamChark** [stereolabs/zed-examples#384]
How to upgrade the firmware？What is the latest firmware version？

**Comment by Myzhar** [comment]
Start ZED Explorer, open settings and select the Firmware tab. Click the upgrade buttons and select the proposed FW. The file with the higher "number" contains the newest available FW

**Comment by YamChark** [comment]
> 启动 ZED 资源管理器，打开设置并选择固件选项卡。单击升级按钮并选择建议的 FW。具有更高"数字"的文件包含最新的可用 FW

1523?

**Comment by Myzhar** [comment]
It is 👍

**Comment by YamChark** [comment]
> 这是👍

The camera is bound to the VR device， How to solve lens shake？
