### ISSUE TITLE
Can I save the result as an obj model in body tracking?

### ISSUE THREAD

**Issue by Kismetzc** [stereolabs/zed-examples#390]
I ran the body tracking demo and saw skeleton in ZED Body Tracking view.  Can I save the result as an obj model?

**Comment by Kismetzc** [comment]
Can I replace Simple3DObject class with my own obj model?  Achieve the effect that my obj model follows my movements.

**Comment by Kismetzc** [comment]
Can I understand it this way? The 3D view is to connect each point of the bones for rendering.
It’s not about having a 3D model, letting the model track the movement.

I am very confused about this and hope to get your help

**Comment by Kismetzc** [comment]
Hi,@qt-truong
I need your help! Can you take a look at this issue when you are free?

**Comment by qt-truong** [comment]
Hello @Kismetzc, sorry for the late reply !

I am very sorry but I am not sure I understand what you are trying to do. Could you please elaborate on your problem ? 

Thanks in advance for your reply

**Comment by Kismetzc** [comment]
Hello @qu-truong,
Thank you for answering right away.

Draw 3D bones in body_tracking.py, it can follow people's movements, now I want to replace the 3D bone model with a 3D human model. Let the 3D human model move with the recognition pose.

I hope I made my confusion clear.

**Comment by Kismetzc** [comment]
![result](https://user-images.githubusercontent.com/52264144/120493547-a2260c00-c3ed-11eb-9916-4623a17c2ce0.jpg)
This is body_tracking.py result.

I want a 3D human model to track my movements instead of the 3D skeleton model

**Comment by Bvallon-sl** [comment]
Hi,

The body tracking sample only creates basic shapes (cylinders and sphere) in order to create a skeleton. It does not handle more complex applications like animating a rigged 3D Model.

I would recommend using our Unity3D plugin which include a example scene that reproduce exactly what you are looking for.
You can find more details about our Unity plugin [here](https://www.stereolabs.com/docs/unity/).

Best regards,
Benjamin Vallon

**Comment by Kismetzc** [comment]
> Hi,
> 
> The body tracking sample only creates basic shapes (cylinders and sphere) in order to create a skeleton. It does not handle more complex applications like animating a rigged 3D Model.
> 
> I would recommend using our Unity3D plugin which include a example scene that reproduce exactly what you are looking for.
> You can find more details about our Unity plugin [here](https://www.stereolabs.com/docs/unity/).
> 
> Best regards,
> Benjamin Vallon

Thanks for your answer! I will try!
By the way, can I achieve the purpose by overriding the `Simple3DObject` class?

**Comment by Kismetzc** [comment]
![v2-77237896caf2af49eec8b56d7b4a24f3_b](https://user-images.githubusercontent.com/52264144/120743044-c89d9180-c52a-11eb-87bb-4895791256c8.gif)
To add, I want to achieve such an effect picture

**Comment by obraun-sl** [comment]
This is exactly what the zed-unity plugin is offering. 
Doing that in C++ by overriding Simple3DObject class is much more complicated since you will basically need to recreate what's inside unity engine.

**Comment by Kismetzc** [comment]
> This is exactly what the zed-unity plugin is offering.
> Doing that in C++ by overriding Simple3DObject class is much more complicated since you will basically need to recreate what's inside unity engine.

OK!

**Comment by Kismetzc** [comment]
> This is exactly what the zed-unity plugin is offering.
> Doing that in C++ by overriding Simple3DObject class is much more complicated since you will basically need to recreate what's inside unity engine.

I ran the demo successfully! Thanks for your help!

**Comment by Kismetzc** [comment]
Hi, @qt-truong 
And I have one more question.
I am still a beginner in OpenGL. Is the skeleton of the 3D perspective obtained by rendering the 2D perspective?
