### ISSUE TITLE
Retrieve Point Cloud Unity 

### ISSUE THREAD

**Issue by au1698** [stereolabs/zed-examples#391]
Hi, 

I am trying to use some lines of this [tutorial:  Using the Depth Sensing API](https://www.stereolabs.com/docs/depth-sensing/using-depth/): to get a 3D point cloud with (X,Y,Z) coordinates.

In the tuturial I found this:  

sl.Mat point_cloud = new sl.Mat();
zed.RetrieveMeasure(point_cloud, MEASURE.XYZRGBA);
float4 point3D = new float4();
// Get the 3D point cloud values for pixel (i,j)
point_cloud.GetValue(i,j, out point3D);
float x = point3D.x;
float y = point3D.y;
float z = point3D.z;
float color = point3D.w;  

 I tried to replicate it in **Unity**: 

point_cloud = new  ZEDMat (); 
point_cloud.Create (1280 , 720,  ZEDMat.MAT_TYPE.MAT_32F_C4 , ZEDMat.MEM.MEM_CPU); 
Camera_Left.RetrieveMeasure(point_cloud , MEASURE.XYZRGBA , ZEDMat.MEM.MEM_CPU); 
float4  point3D;
point_cloud.GetValue (1280/2 ,  720/2 ,  out  point3D , ZEDMat.MEM.MEM_CPU);

 but  the structure of _float4_  seems different  ( not **X,Y,Z,W** but only **R,G,B,A**).  
How do they differ? 
How do I access the _x, y, z_ values?  I would like to access the x,y,z instead.

**Comment by Bvallon-sl** [comment]
Hi,

There is a script called *ZEDPointCloudManager.cs" (available in Assets/ZED/SDK/Helpers/Scripts/Display/) which displays the point cloud in the scene. 

You can use it directly by adding it on a gameobject of your scene. But to answer your question the r,g,b,a attributes and x,y,z,w  are the same : x <-> r, y <-> g, z <->b and w <->a. 

I hope it helps.

Best regards,
Benjamin Vallon
