### ISSUE TITLE
Video export horribly slow on the Jetson Nano platform

### ISSUE THREAD

**Issue by ama-jesper** [stereolabs/zed-examples#392]
_The reason why it is slow:_ 
When "replaying" SVO files for video export, I believe the `grab()` and `retrieve_image()` commands need to decompress the `H264` video frame-by-frame, and then when using OpenCVs `VideoWriter()`-class, as per your examples, we again need to compress each frame. Reading is rather fast, but it is the writing to a video file (compression) that is horribly slow on the Jetson. 

_Question_
Is there a way to directly "pipe" the `H264` video from the SVO-file directly into a video container? Without having to open, read, decompress, compress, write?

**Comment by P-yver** [comment]
Hi,
There is no way to directly convert SVO to standard video files but we provide a sample to do it:
https://github.com/stereolabs/zed-examples/tree/master/svo%20recording/export
To speed up process you can also disable depth computation during the grab:
`init_parameters.depth_mode = sl::DEPTH_MODE::NONE; // no depth computation required here`
