### ISSUE TITLE
Fail to open ZED depth viewer on Win10

### ISSUE THREAD

**Issue by SimonSongg** [stereolabs/zed-examples#393]
I installed the latest SDK 3.5.0 and I cannot run ZED depth viewer. No error, just nothing happened after I run the application.
Win 10, CUDA 10.2, RTX2080super

**Comment by SimonSongg** [comment]
I tried the ZED diagnostic, everything was correct.

**Comment by Myzhar** [comment]
@SimonSongg can you please write an email to support@stereolabs.com adding the report generated by the ZED Diagnostic tool as an attachment?

**Comment by 1187938150** [comment]
When I disconnect the wifi connection, I can open the depth viewer. Otherwise I can't open it.

**Comment by Jeromeh97** [comment]
@SimonSongg Have you sorted this issue? I have the same problem as you had.

**Comment by Myzhar** [comment]
If you are using an antivirus try to disable it.
Some kind of antivirus stop the ZED SDK if not correctly configured.
