### ISSUE TITLE
  "DoneOut of memory" occurs when I download AI mode for Objection Detection

### ISSUE THREAD

**Issue by fy123-gh** [stereolabs/zed-examples#396]
Hi,
https://github.com/stereolabs/zed-examples/tree/master/object%20detection/image%20viewer/cpp
I compiled this C++ example to test object detection function.
My environment is : Ubuntu 16.04, SDK 3.5,CUDA 10.2.
And when I run it, it says:
```
ww@ww-Precision-Tower-7910:~/vpn$ ./ZED_Object_detection_image_viewer 

[ZED][Object Detection] AI model not found, downloading  -Done
 DoneOut of memory
```
Any advice please?

**Comment by adujardin** [comment]
Hi,
Sorry for the late reply, this is probably a CDN issue similarly to this https://github.com/stereolabs/zed-examples/issues/434
The model is not correctly downloaded and fails to load properly. We added a fix and more security in the upcoming version.
