### ISSUE TITLE
Reusing spatial mapping

### ISSUE THREAD

**Issue by YashaAkimov** [stereolabs/zed-examples#397]
Is it possible to save 3d model or point cloud and next time load and reuse it to continue mapping?
Is also possible to use loaded 3d model only for navigation without modifications?

**Comment by P-yver** [comment]
No the spatial mapping can not be saved and then reused.

The Positional Tracking (navigation) algorithm has its own spatial data, which can be saved and then reload: https://www.stereolabs.com/docs/positional-tracking/area-memory/#memorizing-an-area
