### ISSUE TITLE
Lacking example: saving left/right image plus depth map and IMU data with timestamp once a second

### ISSUE THREAD

**Issue by arasharchor** [stereolabs/zed-examples#399]
Hi, I am new to ZED. 

I have a ZED camera and want to install it on a car. I intend to save left/right image plus depth map and IMU data with timestamp at the same time once a second, but I could not find a sample for that in Python3.

Is there any sample which I can use for this purpose to jump in?

**Comment by qt-truong** [comment]
Hi @arasharchor,

- You can have a look at our [depth sensing tutorial](https://github.com/stereolabs/zed-examples/blob/master/tutorials/tutorial%203%20-%20depth%20sensing/python/depth_sensing.py) that will show you how to retrieve images and depth from your camera

- The [sensors data tutorial](https://github.com/stereolabs/zed-examples/blob/master/tutorials/tutorial%207%20-%20sensor%20data/python/sensor_data.py) will show you how to access your ZED IMU data. 

Don't hesitate to visit the [API Reference](https://www.stereolabs.com/docs/api/python/) and modify the tutorials according to your needs

**Comment by luan1412167** [comment]
@arasharchor @qt-truong do you have any script for getting images, depth, IMU together?
