### ISSUE TITLE
Which algorithm is used in positional tracking example ??

### ISSUE THREAD

**Issue by PyojinKim** [stereolabs/zed-examples#4]
Hi, I am currently testing the performance of positional tracking example in this repository.
It really works well!! even though sometimes there are "jumps" in the estimated trajectory.

My question is, what kind of VO algorithm is used in this position tracking example ??
Is it feature-based or direct method with estimated depth image stream ?
It is interesting that there is no (very small) drift error when the ZED camera is stationary.
Is there any related VO paper ?? It is hard to see any related information of position tracking example. 
Could you open some information of the VO algorithm used in position tracking ?

**Comment by pjnet** [comment]
I share the same interest. I want to know which method is used. Is there an article?
Thanks
