### ISSUE TITLE
Can Zed run with CUDA 9.1?

### ISSUE THREAD

**Issue by GGain** [stereolabs/zed-examples#40]
I installed CUDA 9.1 and it always shows me that i need to install cuda 9.0 or missing CUDA in the environment variable.

**Comment by adujardin** [comment]
Hi, 
Unfortunately no, not yet. Until the new ZED SDK 2.3 is released (very soon), you will have to use Cuda 9.0 (with ZED SDK 2.2.1). You can download it [here](https://developer.nvidia.com/cuda-90-download-archive).

**Comment by GGain** [comment]
Thank for your  information.
