### ISSUE TITLE
Make issue for ObjectsBatch

### ISSUE THREAD

**Issue by Baldins** [stereolabs/zed-examples#400]
Hi, 

I m getting the following error after make: 

error: ‘ObjectsBatch’ is not a member of ‘sl’
  sl::Pose world_pose_, sl::Mat image_, sl::Mat pc_, std::vector<sl::ObjectsBatch> &batch_);

Any idea to what is due for?

Thank you! 

Francesca

**Comment by P-yver** [comment]
Hi, 
`sl::ObjectsBatch` has been introduced in [ZED SDK 3.5.0](https://www.stereolabs.com/developers/release/), be sure to have this version.
