### ISSUE TITLE
Where sl_zed / Camera.hpp is located?

### ISSUE THREAD

**Issue by Declining** [stereolabs/zed-examples#41]
Hey ,guys. 
When I tried to compile the code in tutorial, the head file "sl_zed/Camera.hpp" cannot be found. 
So I want to know where I can find this header file, or do I need to create another environment?

**Comment by adujardin** [comment]
Hi,
Replace "sl_zed" by "sl" and it should work (`#include "sl/Camera.hpp"`). 

It was originally meant for the new SDK (2.3) but it's not mandatory anymore. I will fix this in the repository.

**Comment by Declining** [comment]
Thank you, I have solved this problem by you help.

发件人: Aymeric Dujardin<mailto:notifications@github.com>
发送时间: 2018年1月24日 16:31
收件人: stereolabs/zed-examples<mailto:zed-examples@noreply.github.com>
抄送: Declining<mailto:DecliningAristocrat@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [stereolabs/zed-examples] Where sl_zed / Camera.hpp is located? (#41)


Closed #41<https://github.com/stereolabs/zed-examples/issues/41> via 398893d<https://github.com/stereolabs/zed-examples/commit/398893d538e35324a19076543947383dfe9b82d8>.

―

**Comment by schliffen** [comment]
It was not fixed yet, I'm still facing with that error!

**Comment by obraun-sl** [comment]
Make sure that the ZED SDK include directory is in the include directories list. If using Cmake , it should be automatically done.
For example, under windows, the include dir is C:/Program Files(x86)/ZED SDK/include

**Comment by Vizalkar** [comment]
Hi
I encountered the same error and i use cmake.
It is not solvec, the directory in ZED SDK is "sl", not "sl_zed".
Changing the #include "sl_zed/*" lines does the trick
