### ISSUE TITLE
How to save multiple frames of data in the same .npy file?

### ISSUE THREAD

**Issue by Kismetzc** [stereolabs/zed-examples#413]
I don’t understand why I can get the data of the next frame by pressing the Enter key [in this code](https://github.com/stereolabs/zed-examples/blob/650cef365e9dbfd71760d9874cb80e3a27ad9f30/tutorials/tutorial%208%20-%20body%20tracking/python/body_tracking.py#L102)

Now, I want to save the keypoint of each frame to .npy file, what should I do?

**Comment by qt-truong** [comment]
Hello @Kismetzc,

Sorry for the late reply. 
The script uses the Python built-in method `input()` that waits for the user's input before continuing. (You can check this [documentation](https://docs.python.org/3/library/functions.html#input) )
The attibutes `keypoint` and `keypoint_2d` are output as numpy arrays, and according to [numpy documentation](https://numpy.org/doc/stable/reference/generated/numpy.save.html), you can simply call `keypoint.save("my_file.npy")`.
You just need to make sure you change your filename at each iteration.
