### ISSUE TITLE
Timestamp of grab() is stably about 80ms slower than the current system time

### ISSUE THREAD

**Issue by nonononentity** [stereolabs/zed-examples#425]
Hi All,

When I built my own program with function zed.grab() , I found the obtained timestamp of image is stably about 80ms slower than the current system time. Why?
(HD720, Performance Depth, 15fps, zed2)

And if I want to get an RGB and depth map of zed at the current time, should I compensate for the timestamp provided by ZED( + 80ms？)?
Thanks,

**Comment by Myzhar** [comment]
Hi @nonononentity, how did you measure the latency?
