### ISSUE TITLE
win10 C++ environment configuration 

### ISSUE THREAD

**Issue by nankaiyoutian** [stereolabs/zed-examples#427]
I don't figure out why I can't find Core.hpp, Mesh.hpp, types.hpp, defines.hpp in my "sl" folders, what should I do?
thanks

**Comment by obraun-sl** [comment]
Did  you install the ZED SDK with the windows installer?
The files should be located in C:/Program Files (x86)/ZED SDK/include/
Can you make sure they are effectively here ? Also make sure to reboot your PC once the SDK is installed so that Windows PATH are updated.

**Comment by nankaiyoutian** [comment]
Yes, I install the zed sdk successfully.
however, there is only one file named "Camera.hpp"

**Comment by P-yver** [comment]
Now only `Camera.hpp` is distributed, it contains all previously separated files.
