### ISSUE TITLE
Object Detection] AI model not found, downloading failed

### ISSUE THREAD

**Issue by nankaiyoutian** [stereolabs/zed-examples#428]
I'm running object Detection in win10 C++, AI model not found, downloading —— it is successful.
but why "[Object Detection] Please wait while the AI model is being optimized for your graphics card
 This operation will be run only once and may take a few minutes" failed?
the error goes in "	returned_state = zed.enableObjectDetection(obj_det_params);
	if (returned_state != ERROR_CODE::SUCCESS) {
		print("enable Object Detection", returned_state, "\nExit program.");
		zed.close();
		return EXIT_FAILURE;
	}"
ant it collapses.

**Comment by adujardin** [comment]
Could you give more detail about the message and error type you get when the optimization fails?

Turning on verbose mode may help getting more information (using [`InitParameters.sdk_verbose`]( https://www.stereolabs.com/docs/api/structsl_1_1InitParameters.html#a9dde673d011f8a9504487eb5f1eb9856))
