### ISSUE TITLE
Custom detector python

### ISSUE THREAD

**Issue by Sujay-Mhaske** [stereolabs/zed-examples#438]
### Preliminary Checks

- [x] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, bug report, or anything other than a feature request directly related to this project.

### Proposal

Please add custom detector sample program in python in yolov5,tensorflow to get 3d bounding box dimensions , currently its is only in cpp.

**Comment by jvnsg** [comment]
@Sujay-Mhaske have you managed to get up a running code? 
We encounter some issues and can't verify the cause.

**Comment by Myzhar** [comment]
Just released:
https://github.com/stereolabs/zed-examples/tree/master/object%20detection/custom%20detector/python/pytorch_yolov5

**Comment by jvnsg** [comment]
@Myzhar thanks guys, this is an incredible support!

**Comment by Sujay-Mhaske** [comment]
Thank you , so much !!!!!!!!!!!!!!!!!!!!!
