### ISSUE TITLE
"OpenCV Error: Assertion failed" For "Tutorial 6: Object Detection with the ZED 2"

### ISSUE THREAD

**Issue by zhan6841** [stereolabs/zed-examples#440]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

I was trying to run the [objection detection tutorial code](https://github.com/stereolabs/zed-examples/tree/master/tutorials/tutorial%206%20-%20object%20detection). However, I was always having the same output for each grabbed image, as follows:

```
OpenCV Error: Assertion failed (0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows) in Mat, file /builds/sl/ZEDKit/lib/src/sl_core/opencv/core/matrix.cpp, line 508
Error /builds/sl/ZEDKit/lib/src/sl_core/opencv/core/matrix.cpp:508: error: (-215) 0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows in function Mat
detect 
0 Object(s) detected
```

**Is this one of the expected outputs? If not, how can I fix it?**

### Steps to Reproduce

1. Download ZED SDK v3.6.1 for Ubuntu 18.04 with CUDA Version 10.2
2. Follow the instruction [here](https://www.stereolabs.com/docs/installation/linux/) to install ZED SDK
3. clone and compile the github [repo](https://github.com/stereolabs/zed-examples)
4. compile the code under "tutorial/":
```
cd zed-examples-master/tutorials
mkdir build
cd build
cmake -DCMAKE_LIBRARY_PATH=/usr/local/cuda/lib64/stubs
make
```
5. Run tutorial 6

### Expected Result

At least there should not be something like "OpenCV Error: Assertion failed".

### Actual Result

For each grabbed image, the output is as follows:

```
OpenCV Error: Assertion failed (0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows) in Mat, file /builds/sl/ZEDKit/lib/src/sl_core/opencv/core/matrix.cpp, line 508
Error /builds/sl/ZEDKit/lib/src/sl_core/opencv/core/matrix.cpp:508: error: (-215) 0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows in function Mat
detect 
0 Object(s) detected
```

### ZED Camera model

ZED2i

### Environment

```shell
OS: Ubuntu LTS 18.04
ZED SDK Version: 3.6.1
CUDA Version: 10.2
OpenCV Version Installed in my system: 3.2 (But I guess the OpenCV used by ZED SDK should be different from this one?)
```

**Comment by crmaxj** [comment]
Little late to the party here, but we had this issue, and it turned out that the bounding boxes sent back from our model were sometimes out of bounds by a couple pixels. As a quick hack to fix the issue, you can patch the example like:

```
                // Preparing for ZED SDK ingesting
                std::vector<sl::CustomBoxObjectData> objects_in;
                cv::Rect bounds = cv::Rect(0, 0, left_cv_rgb.size().width, left_cv_rgb.size().height);

                for (auto &it : res) {
                    sl::CustomBoxObjectData tmp;
                    cv::Rect r = get_rect(left_cv_rgb, it.bbox);

                    // Ensure r doesn't go out of bounds
                    r = bounds & r;

...
```
