### ISSUE TITLE
Manual filtering using texture confidence

### ISSUE THREAD

**Issue by Andrei-Lapusteanu** [stereolabs/zed-examples#444]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, bug report, or anything other than a feature request directly related to this project.

### Proposal

Hello! I am not entirely sure if what I propose can already be achieved, but I could not code this in / find an answer, and as I do not think this is a bug, I am writing this in the form of a feature request.

I am trying to manually filter data (such as depth or point cloud data) using the **Texture Confidence** data. 

I am aware that I can filter the data using `sl::RuntimeParameters::confidence_threshold` and `sl::RuntimeParameters::texture_confidence_threshold`, but these filter out points which do not meet the thresholds, which I do not want.

I am also aware I can retrieve the **Confidence Measurement** using the `retrieveMeasure` function - but this only gives me access to filter the data using the **Confidence** data. I cannot find a way to set both the `confidence_threshold` and `texture_confidence_threshold` to 100 and then manually filter using the **Texture Confidence**.

If this is not currently possible, I would like to request this feature.

**EDIT:** I have found (albeit, a very silly 😅) work-around for this, which involves multiple `grab` calls per frame - during which I have identified another problem - I will file a bug report (if suitable) with my findings after I investigate a little further.

### Use-Case

This would allow to **manually** filter the data using the **Texture Confidence** (as of now, manual filtering can be achieved using only the **Confidence**).

**Comment by P-yver** [comment]
Hi,
Changing the value of `sl::RuntimeParameters::confidence_threshold` will internally use the data of `MEASURE::CONFIDENCE` to filter the disparity/depth in output.
Currently the confidence Mat related to `sl::RuntimeParameters::texture_confidence_threshold` can not be retrieved, is this what you want?

**Comment by Andrei-Lapusteanu** [comment]
Hi @P-yver, thank you for the response!

Yes, this is the information I would have liked to retrieve (related to `sl::RuntimeParameters::texture_confidence_threshold`). I have managed to force this by doing 2 grab calls per frame. In the first call I retrieve an image filtered using the texture confidence, and in the second grab, in which I use the points filtered in the first step, I do the rest of my processing. But this is a viable solution only if I run my application offline (using an .svo recording), it's not suitable for real-time acquisition.

**Comment by Nunzio03** [comment]
I Think this Issue should be opened again, as having a retrievable texture confidence map would be useful in certain real-time applications.
In my case I'm dynamically filtering the point cloud in order to get just a sub-set of points with a higher confidence, but i do not want to filter the point-cloud a priori by giving a texture_confidence_treshold, i want to be able to choose how to filter based on the texture confidence map.

Is that just used internally? and if it is so, why is it not returnable to the user?
