### ISSUE TITLE
Body tracking sample code does not work

### ISSUE THREAD

**Issue by 7uk3** [stereolabs/zed-examples#445]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

When running the body_tracking.py code in the samples folder, an error occurs: 
freeglut (foo): ERROR: Internal error <FBConfig with necessary capabilities not found> in function fgOpenWindow
![Terminal when running body_tracking py](https://user-images.githubusercontent.com/94495910/142088746-b2d2ad6f-2b97-4815-badc-01ec613661bb.png)
The error occurs on line 86, of the body_tracking.py file, which goes into the viewer.py file. The error occurs on line 459 of the viewer.py file, as when i ran through the debugger one line at a time, this is when the error occurred. 
![Where code fails in body_tracking py](https://user-images.githubusercontent.com/94495910/142088749-9fd79c24-09f8-4aa9-ac88-4042cc5ac5b2.png)
![when error occurs in viewer py file](https://user-images.githubusercontent.com/94495910/142088747-4bcb63f5-0f4c-4be5-b939-5a9eed97f0af.png)
I have been able to use the rest of the sample codes provided with the camera, such as the object detection image viewer, which is able to create a window to view what the camera is producing without fail. I also uninstalled and reinstalled OpenGL in case there was a problem with the initial install.

### Steps to Reproduce

1. Open body_tracking.py file in VSCode.
2. Run the body_tracking.py file
3. error occurs

### Expected Result

Window opens and when person is in frame, skeleton is created.

### Actual Result

freeglut (foo): ERROR: Internal error <FBConfig with necessary capabilities not found> in function fgOpenWindow appeared in the terminal
![Terminal when running body_tracking py](https://user-images.githubusercontent.com/94495910/142088715-055dd760-01ee-4748-9709-246f384a0566.png)

### ZED Camera model

ZED2i

### Environment

```shell
OS: ubuntu 18.04
CPU: Nvidia Jetson Nano Kit
GPU: Nvidia Jetson Nano Kit
ZED SDK: 3.61 (SDK for JetPack 4.6)
JetPack (4.6)
VSCode (1.62)
OpenCV (4.5.4)
OpenGL (4.6.0 Nvidia 32.6.1)
Python (3.6.9)
```

**Comment by qt-truong** [comment]
Hi @7uk3,

The error you get is very odd since de Object Detection image viewer and the Body Tracking viewers are very similar and need the same configuration.
As a workaround, could you please try to run this sample inside a docker container to see if it helps ? You can find instructions on how to do that on [zed-docker](https://github.com/stereolabs/zed-docker#jetson-images) repo and the images are listed [here](https://hub.docker.com/r/stereolabs/zed)
