### ISSUE TITLE
setCameraSettings only affect the left camera?

### ISSUE THREAD

**Issue by DannyYCCheng** [stereolabs/zed-examples#45]
In Linux, sl::setCameraSettings() seems to only affect the left camera? Have tried this in my own code as well as sample/camera_control/ , where I changed VIEW_LEFT to VIEW_RIGHT for zed.retrieveImage().

**Comment by adujardin** [comment]
Hi,
Yes, this is a known issue in 2.3.0. A fix was released in 2.3.1, available here: https://www.stereolabs.com/developers/release/2.3/
