### ISSUE TITLE
Error while loading shared libraries "libsl_input.so". Cannot open shared object file. No such file directory

### ISSUE THREAD

**Issue by LoayMAmin** [stereolabs/zed-examples#46]
I'm having trouble executing the file "ZED Explorer". And I keep getting this error. Please advice.

**Comment by LoayMAmin** [comment]
Free up some space.
The problem was during installation, the Jetson simply ran out of memory and couldn't load this library.

**Comment by 459737087** [comment]
hello! I also met this problem , but the space is free .
