### ISSUE TITLE
C# sample doesn't work.

### ISSUE THREAD

**Issue by hagsac** [stereolabs/zed-examples#466]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

"nuget 3.7 is not installed" is displayed.
I changed it to 3.6 but the execution failed.

![image](https://user-images.githubusercontent.com/75370807/155627775-0209ef2a-359c-4c9f-ad9b-6380e14f1790.png)

### Steps to Reproduce

1. vs2022
2. sdj 3.7
3. cmake install
4. nuget error
...

### Expected Result

normal behavior

### Actual Result

![image](https://user-images.githubusercontent.com/75370807/155627915-286cbe6a-104f-4948-915d-471e9545e0f5.png)

### ZED Camera model

ZED2i

### Environment

```shell
win 10 pro
1660 ti
16gb ram
sdj 3.7
example c#
```

**Comment by Bvallon-sl** [comment]
Hi, 
the nuget package for 3.7 is not available yet.

It will be published today.

Best.
Benjamin V.

**Comment by Bvallon-sl** [comment]
It has now been published and will be available soon after validation.
Do not hesitate to contact us if you still have issues using the nuget package.

Best regards,
Benjamin Vallon
