### ISSUE TITLE
Keypoints are not stored while body tracking. 

### ISSUE THREAD

**Issue by icsl-Jeon** [stereolabs/zed-examples#467]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

How can this happen? I encountered many cases where the keypoints are set to nan. 
But in which cases I get empty keypoints? I tried 18 and 34 both. 

Hope you can give me the clue.  
Regard. 

### Steps to Reproduce

1.
2.
3.
...

### Expected Result

keypoint.size() == 34 or 18

### Actual Result

0

### ZED Camera model

ZED2

### Environment

```shell
Windows 10 
SDK 3.7
```

**Comment by P-yver** [comment]
Hi,
In some cases, all keypoints cannot be detected (hidden by other objetcs), or their 3D positions can not be estimated, in this case they are filled with nan values.
