### ISSUE TITLE
NEURAL Depth mode supported?

### ISSUE THREAD

**Issue by AndreV84** [stereolabs/zed-examples#471]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, bug report, or anything other than a feature request directly related to this project.

### Proposal

add NEURAL Depth mode

### Use-Case

save more detailed 3d map processed by NEURAL mode

**Comment by Myzhar** [comment]
@AndreV84 can you please add more details?

**Comment by Myzhar** [comment]
You can set depth mode to NEURAL by changing the relative depth mode parameter:
https://github.com/stereolabs/zed-examples/blob/master/spatial%20mapping/advanced%20point%20cloud%20mapping/cpp/src/main.cpp#L46

**Comment by AndreV84** [comment]
@Myzhar 
Thank you for your reply
Is there a chance to just add one line to the basic example code?
after the line https://github.com/stereolabs/zed-examples/blob/ed3f068301fbdf3898f7c42de864dc578467e061/spatial%20mapping/basic/cpp/src/main.cpp#L46 
?
``` 
init_parameters.depth_mode = DEPTH_MODE::NEURAL;

**Comment by Myzhar** [comment]
It's an example code, you can adapt it to your requirements without problems.

**Comment by AndreV84** [comment]
so lets close the issue
