### ISSUE TITLE
ZEDfu camera settings, not clickable

### ISSUE THREAD

**Issue by altineller** [stereolabs/zed-examples#476]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

When capturing for depth sensing or spatial mapping, I would like to play with the settings of camera, like brightness, contrast, etc.

Depending on the light and room conditions, one can get much better results by applying principles of general photography.

Right, now I go to zedexplorer, setup the details, then open another zedfu or 3d depth sensing program to get results.

Is there anyway, or rather, what would our workflow need to be in order to make adjustments on zed2i camera.

Best Regards,
C.

### Steps to Reproduce

1. Start ZEDfu
2. Open settings
3. Click camera
...

### Expected Result

camera settings dialog open

### Actual Result

nothing happens

### ZED Camera model

ZED2i

### Environment

```shell
ubuntu 20.04
cpu: x86_64
gpu: nvidia rtx2060
sdk version: 372
```

### Anything else?

ZEDfu also will not record defaults.

**Comment by obraun-sl** [comment]
Best would be to use the spatial mapping sample
https://github.com/stereolabs/zed-examples/tree/master/spatial%20mapping/basic/cpp

and add the Camera::setCameraSettings() function
https://www.stereolabs.com/docs/api/classsl_1_1Camera.html#ae8d5655803778feebfe159912f09be07
