### ISSUE TITLE
New SDK can't build the sample.

### ISSUE THREAD

**Issue by 459737087** [stereolabs/zed-examples#479]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

in /zed/samples/tutorial/ttutorial-3-depth sensing/build.
when I cmake ..
It reported.
![2022-04-24 16-24-14屏幕截图](https://user-images.githubusercontent.com/54131759/164967426-636d5c58-7daa-4def-b325-19fac67c59ad.png)

### Steps to Reproduce

mkdir build
cd build
cmake ..

### Expected Result

goes right

### Actual Result

bug

### ZED Camera model

ZED

### Environment

```shell
os:ubuntu 20.04
zed: 3.7
cuda: 11.5
```

**Comment by Myzhar** [comment]
Did you update from an older SDK version? In this case you must clean the CMake cache by deleting the content of your build folder.
Then you must call the `cmake ..` command again and finally recompile.

**Comment by 459737087** [comment]
Hello @Myzhar ! the SDK version is the newest , and I deleted the build folder and recompile , but this problem still generate.

**Comment by Myzhar** [comment]
Have you tried to install the BLAS libraries?
```
sudo apt-get update
sudo apt-get install -y libopenblas-dev
```

PS Always copy and past the full error log, screenshot are not a good way of providing error information,

**Comment by 459737087** [comment]
Hi! I have tried to install BLAS libraries, that problem has solved, but a new problem raised.
[CMakeError.log](https://github.com/stereolabs/zed-examples/files/8549336/CMakeError.log)
[CMakeOutput.log](https://github.com/stereolabs/zed-examples/files/8549337/CMakeOutput.log)

**Comment by obraun-sl** [comment]
Hi,
You need to add pthread in the target link libraries list
https://github.com/stereolabs/zed-examples/blob/master/tutorials/tutorial%203%20-%20depth%20sensing/cpp/CMakeLists.txt#L39

It should be `TARGET_LINK_LIBRARIES(${PROJECT_NAME} ${ZED_LIBS} pthread)`

**Comment by 459737087** [comment]
Thank u! I have solved it.
