### ISSUE TITLE
AI Models not working on Jetson AGX Cuda 10.0

### ISSUE THREAD

**Issue by sumitsarkar1** [stereolabs/zed-examples#485]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

After running ZED_Diagnostics (or ZED_Depth_Viewer) , the diagonastics crashes at the stage of checking AI Models and throws the following error

`libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Stack trace (most recent call last) in thread 16140:
#4    Object "/lib/aarch64-linux-gnu/libpthread.so.0", at 0x7f910bd087, in 
#3    Object "/usr/lib/aarch64-linux-gnu/libstdc++.so.6", at 0x7f905f3e93, in 
#2    Object "./ZED_Diagnostic", at 0x42f73f, in DiagnosticRunner::runDiagnostic(DiagnosticRunner*)
#1    Object "./ZED_Diagnostic", at 0x451bb3, in 
#0    Object "./ZED_Diagnostic", at 0x45e390, in 
Segmentation fault (Address not mapped to object [(nil)])
Segmentation fault (core dumped)
`

### Steps to Reproduce

1.
2.
3.
...

### Expected Result

Expected ZED_Diagnosis to run completely

### Actual Result

ZED_Diagnosis starts...green ticks on 1. ZED SDK 2. Processor 3. Graphics Card  ...then the application crashes for AI Models

 ldd libsl_ai.so gives `ldd: ./libsl_ai.so: No such file or directory`
### ZED Camera model

ZED2i

### Environment

```shell
Hardware : Jetson AGX Tegra
OS : Ubuntu 18.04 LTS
CUDA : 10.0 
SDK : ZED SDK for L4T 32.3 (Jetpack 4.3) 3.7.2
```

**Comment by adujardin** [comment]
The tools shouldn't crash but the AI module is not compatible with CUDA 10.0 and Jetpack 4.3 as they are legacy installers and no longer supported for this module. You should upgrade the jetpack version if possible (the newer the jetpack the better the performance will be, especially for AI module)
