### ISSUE TITLE
Left SVO to .AVI conversion not working

### ISSUE THREAD

**Issue by SalvishGoomanee** [stereolabs/zed-examples#488]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

I am trying to save a .svo video and export the only the left image as a .avi file. 

I have information which appears on the screen by using `cv2:putText()` module on execution. 

However, this information is not present anymore in the saved .svo file. 

I only see the usual ZED left and right displays. 

Using the SVO export commands, I keep getting errors in cmd. 

Using the SVO.exe module for exporting, I am able to export the left image indeed into a .avi file but I loose all information on the screen and the fps is very fast.

I would to modify to the video_export.py script but I am not sure how to then implement it for left image export to .avi.

### Steps to Reproduce

In cmd for saving the left image I run: 

`python main.py testing.svo`

For exporting  I run:

`ZED_SVO_Export testing.svo testing.avi 1` 
(Like indicated this is not optimal since it is exporting (when using the `.exe` from the bin folder) both LEFT and RIGHT images and I think this is causing the loss in data that should be on the screen).

### Expected Result

Expect a .avi file with left image but file is corrupted. 

### Actual Result

I get the following error when running from cmd: 

`'ZED_SVO_Export' is not recognized as an internal or external command,
operable program or batch file.
`

When using the `.exe`, the .avi video file lacks data. 

### ZED Camera model

ZED2i

### Environment

```shell
OS: Python 3.9
GPU: NVIDIA GEFORCE RTX
ZED_SDK: Version 3.6.2
```

**Comment by obraun-sl** [comment]
Hi,
The SVO file is a video file that stores only the raw image from the camera. Therefore it will not contain modifications made on the image itself as it's not its purpose. If you want to save a standard video file (mp4), then you need to get the image from the ZED SDK (retrieveImage), convert to OpenCV mat (slMat2cvMat function / numpy copy), modify the cv Mat and save **this** cvMat into a video file. 
If you don't have the correct FPS, you need to specify the same FPS in the videowriter constructor than the SVO/camera.
