### ISSUE TITLE
ZED explorer for Ubuntu?

### ISSUE THREAD

**Issue by jvgomez** [stereolabs/zed-examples#49]
The ZED explorer has some utilities which are nice, like recording lossless video at different resolutions. While I guess this is possible by coding, I wonder if there is something similar in Ubuntu, as the svo recorder does not provide such options.

**Comment by obraun-sl** [comment]
Hi,

ZED Explorer (and all the tools) is also available on Ubuntu, under /usr/local/zed/tools/  and provides the same option as on Windows. You can then record lossless svo on Ubuntu as well

OB

**Comment by jvgomez** [comment]
Ouch! I saw the samples but didn't see that. Good to know. Thanks!
