### ISSUE TITLE
gl.GLViewer().init() crashing on some zed-examples scripts (FBConfig with necessary capabilities not found)

### ISSUE THREAD

**Issue by kimzed** [stereolabs/zed-examples#496]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

I am running different scripts from the zed-examples. i worked with positional_tracking that worked without issue.

I am trying to work with the object-detection folder, but when initializing the gl.GLViewer, I get this error:

 ERROR:  Internal error <FBConfig with necessary capabilities not found> in function fgOpenWindow

I suppose this has to do with the viewer.py files in the ogl_viewer folders.

I run this on a linux machine

### Steps to Reproduce

run for example the file image_detection_file_viewer.py

### Expected Result

opengl window is opening 

### Actual Result

 ERROR:  Internal error <FBConfig with necessary capabilities not found> in function fgOpenWindow

program closes

### ZED Camera model

ZED2i

### Environment

```shell
Os: Ubuntu 20.04.4 LTS (Focal Fossa)
cpu: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
gpu: TU106 [GeForce RTX 2060]
zed sdk version : 3.6
```

### Anything else?

gl.GLViewer is different for every zed-example folder, so I expected there is an issue in the object detection gl.GLViewer scripts

**Comment by Myzhar** [comment]
Hi @kimzed 
what is the exact version of the ZED SDK that you are using? 3.6.4?

**Comment by kimzed** [comment]
from conda list: pyzed                     3.6                      pypi_0    pypi

**Comment by kimzed** [comment]
So i looked into the files a bit and it seems that this line causes issues:

glutInitDisplayMode(GLUT_DOUBLE | GLUT_SRGB | GLUT_DEPTH)

If i change into this: 

glutInitDisplayMode(GLUT_DOUBLE | GLUT_RGBA | GLUT_DEPTH)

the glutCreateWindow("ZED Object Detection") is working

**Comment by Myzhar** [comment]
> @Myzhar from conda list: pyzed 3.6 pypi_0 pypi

This is the version of the pyzed library, you can easily find the version of the ZED SDK that you are using by starting ZED Explorer and looking at the status bar bottom left.

Have you tried the latest ZED SDK v3.7.2 to check if the problem is still present?

**Comment by alanantony6174** [comment]
facing the same problem
 python3 spatial_mapping.py 
[Sample] Using default resolution
[2024-11-11 12:26:33 UTC][ZED][INFO] Logging level INFO
[2024-11-11 12:26:33 UTC][ZED][INFO] Logging level INFO
[2024-11-11 12:26:33 UTC][ZED][INFO] Logging level INFO
[2024-11-11 12:26:34 UTC][ZED][INFO] Using USB input... Switched to default resolution HD720
[2024-11-11 12:26:34 UTC][ZED][INFO] [Init]  Depth mode: NEURAL
[2024-11-11 12:26:35 UTC][ZED][INFO] [Init]  Camera successfully opened.
[2024-11-11 12:26:35 UTC][ZED][INFO] [Init]  Camera FW version: 1523
[2024-11-11 12:26:35 UTC][ZED][INFO] [Init]  Video mode: HD720@60
[2024-11-11 12:26:35 UTC][ZED][INFO] [Init]  Serial Number: S/N ********
freeglut (foo):  ERROR:  Internal error <FBConfig with necessary capabilities not found> in function fgOpenWindow
