### ISSUE TITLE
no data in converted video or image

### ISSUE THREAD

**Issue by DamonMIN** [stereolabs/zed-examples#5]
Dear sir,
When converted the svo file into video or image,  I got the empty result. As the following picture shows.
![_0](https://cloud.githubusercontent.com/assets/14936902/25517706/2ec22796-2c23-11e7-9364-4871c31dd4ad.png)

**Comment by michela** [comment]
Same here. Is this project live?

**Comment by nesnes** [comment]
Corrected in 3ef0e7d. (same as issue #7)

Thanks for the report.
