### ISSUE TITLE
Can I use ZED-sdk to obtain video frame and sensor data on Raspberry-Pi ? 

### ISSUE THREAD

**Issue by yyjFish** [stereolabs/zed-examples#500]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, bug report, or anything other than a feature request directly related to this project.

### Proposal

only use ZED-sdk to get video frame and sensor data (imu data and magnetometer data) , not required depth sensing or other high computational consumption method

**Comment by Myzhar** [comment]
Hi @yyjFish 
the ZED SDK requires CUDA. You can use the [zed-open-capture driver](https://github.com/stereolabs/zed-open-capture).
IT does not provide all the features of the ZED SDK, but it allows you to get image frames and sensors data
