### ISSUE TITLE
CAMERA MOTION SENSORS NOT DETECTED

### ISSUE THREAD

**Issue by robomike** [stereolabs/zed-examples#504]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

 python3 zed_sensor_data.py 
can't claim interface 0: -6
CAMERA MOTION SENSORS NOT DETECTED

I've tried to debug this issue by looking deeper into it. 
Running the ZED Diagnostic tool results in:
[ZED][WARNING] libhid error: -6
can't claim interface 0: -6

So perhaps this is an SDK issue?
sudo lshw yields:
`*-usb:0
          description: USB hub
          product: USB 2.0 Hub
          vendor: Standard Microsystems Corp.
          physical id: 2
          bus info: usb@1:2
          version: b.b3
          capabilities: usb-2.00
          configuration: driver=hub maxpower=2mA slots=2 speed=480Mbit/s
        *-usb UNCLAIMED
             description: Human interface device
             product: ZED-2i HID INTERFACE
             vendor: STEREOLABS
             physical id: 2
             bus info: usb@1:2.2
             version: 3.0a
             serial: 32142444
             capabilities: usb-2.00
             configuration: maxpower=150mA speed=12Mbit/s
`
which means the kernel isn't loading the driver, or doesn't know what it is.

I've tried to reinstall the SDK and this still is not working.

I tried running the ZED Diagnostic on the machine with cables in both directions... see attached.
[ZED_Diagnostic_Results.zip](https://github.com/stereolabs/zed-examples/files/9212912/ZED_Diagnostic_Results.zip)

Is there a known working configuration?

### Steps to Reproduce

1. Fresh Jetson Nano 2GB install with JP 4.6.1
2. install dependencies and ZED_SDK_Tegra_L4T32.7_v3.7.4.run
3. reboot
4. run  python3 zed_sensor_data.py 
...

### Expected Result

I expect this to work with no issues.

### Actual Result

can't claim interface 0: -6
CAMERA MOTION SENSORS NOT DETECTED

### ZED Camera model

ZED2i

### Environment

```shell
OS:  Ubuntu 18.04
NVIDIA JETSON NANO 2GB
JP 4.6.1
```

**Comment by AlexanderKhazatsky** [comment]
having this same issue
