### ISSUE TITLE
ZEDfu is not able to attach texture

### ISSUE THREAD

**Issue by robot-Yang** [stereolabs/zed-examples#505]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

Actually there are two issues I want to ask:

1. In ZEDfu, I started building mesh, when I click stop, the error happens: "Invalid mesh file" as shown below: 
![image](https://user-images.githubusercontent.com/9564889/182034286-f230bacb-0244-4b6b-982a-f067176e2e4c.png)

3. Previous [ZEDfu (ZED SDK 1.0)](https://www.youtube.com/watch?v=AFH2yN3rM78) is able to attach texture online, the current version cannot, may I know why?

### Steps to Reproduce

1. Open ZEDfu
2. Click Input
3. Select Live
4. Start
5. Stop
...

### Expected Result

1. Build the entire Mesh

2. It could be nice if ZEDfu can attach texture to mesh real-time.

### Actual Result

Mesh build failed.

No real-time texture.

### ZED Camera model

ZED Mini

### Environment

```shell
OS	        Windows 11
Processor	11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz   2.30 GHz
Installed RAM	16.0 GB (15.8 GB usable)
System type	64-bit operating system, x64-based processor
ZED SDK         3.7
```

**Comment by geyihuii** [comment]
Hello, have you solved this problem, I have also encountered this problem.
