### ISSUE TITLE
Coregistered point cloud of entire scene from ZED image sequences in .svo file?

### ISSUE THREAD

**Issue by gcutt** [stereolabs/zed-examples#52]
I need to get a full point cloud from a ZED image sequence recorded to .svo file. 
I can export points from individual frames, using the ZED Depth Viewer or using some of the ZED SDK and github examples that I've built myself.  However, I need points for the entire scene captured in the sequence, not just partial views from individual frame pairs. 
What is the best way to get co-registered, dense point clouds of an entire scene from image sequences in .svo files, so that points are globally registered?  Is this possible using ZED SDK tools, only? 
Note, I have produced meshes from .svo files and from real-time camera imagery, and can save these as .obj files, but the meshes are not detailed enough for my purposes. 

Thank you, 
George

**Comment by WASCHMASCHINE** [comment]
Simplest way would be to use the estimated camera pose and backproject all pixels according to the current frame pose.
