### ISSUE TITLE
ImportError: cannot import name 'scale_coords' from 'utils.general'

### ISSUE THREAD

**Issue by davidEXOM** [stereolabs/zed-examples#531]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

I am trying to execute the detector.py script with some weights I alredy have but when I try to execute the command python detector.py --weights myweights.pt the next error jumps:
File "/path/to/zed-examples/object detection/custom detector/python/pytorch_yolov5/detector.py", line 14, in <module>
    from utils.general import check_img_size, non_max_suppression, scale_coords, xyxy2xywh
ImportError: cannot import name 'scale_coords' from 'utils.general' (/path/to/zed-examples/object detection/custom detector/python/pytorch_yolov5/./yolov5/utils/general.py)

I have entered the general.py script and searched for the function named scale_coords but it does not exist there are only the functions scale_boxes or sclae_segments.

### Steps to Reproduce

1. Install the zed repository
2. Inside Zed/object_detection/custom detector/python/pytorch execute detector.py
3. Get the error

### Expected Result

I expected not to have errors and the script to execute 

### Actual Result

The next error, no function exists with name scale_coords:
File "/home/nvidia/Documents/GITLAB/zed-examples/object detection/custom detector/python/pytorch_yolov5/detector.py", line 14, in <module>
    from utils.general import check_img_size, non_max_suppression, scale_coords, xyxy2xywh
ImportError: cannot import name 'scale_coords' from 'utils.general' (/home/nvidia/Documents/GITLAB/zed-examples/object detection/custom detector/python/pytorch_yolov5/./yolov5/utils/general.py)

### ZED Camera model

ZED2i

### Environment

```shell
linux_aarch64
Python 3.10.9
ZED SDK 3.8
```

**Comment by TheodorEmanuelsson** [comment]
This is because Yolov5 has had a major update which changes a lot of the code that this example depends on. We noted the same thing in issue #529 and made a pull request #530 to solve the problem. This PR however relies on using Yolov7 instead of Yolov5 so its not a perfect solution if your weights are made for V5. 

Another thing you could do is to rewrite the `detector.py` to support the new V5 version or clone an older version of the V5 repo.
