### ISSUE TITLE
Native binaries in NuGet are in wrong folder

### ISSUE THREAD

**Issue by joreg** [stereolabs/zed-examples#533]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

The native binaries in the nuget found here: https://www.nuget.org/packages/Stereolabs.zed
are in the wrong folder.

They are in: 

    runtimes\windows10-x64\

But must be in:

    runtimes\windows10-x64\native\

### Steps to Reproduce

1. Download the nuget
2. Inspect and see that they are in the wrong folder
3.
...

### Expected Result

They should be in the correct folder as described here: [Architecture-specific folders](https://learn.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks#architecture-specific-folders)

### Actual Result

Native binaries in NuGet are in wrong folder

### ZED Camera model

ZED

### Environment

```shell
OS: Windows
```

**Comment by Bvallon-sl** [comment]
Hi,

Thanks for the report.

This will be fixed for the next SDK release!

Best regards.
