### ISSUE TITLE
Error NO GPU COMPATIBLE, exit program.

### ISSUE THREAD

**Issue by junsukha** [stereolabs/zed-examples#536]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

I run tutorial 1 code on Windows with CUDA 11.7 installed.
I installed ZED SDK 3.8.2. 

When I run the tutorial, I have the following error.
`Error NO GPU COMPATIBLE, exit program.`

### Steps to Reproduce

I think it's related to the issue that when I run "ZED Depth Viewer", it has this message at top

![image](https://user-images.githubusercontent.com/24444240/219931390-fbab8ee1-9384-4add-88d9-aae46b60e9ea.png)   

### Expected Result

 But when I run `nvidia-smi`,  

![image](https://user-images.githubusercontent.com/24444240/219931495-3bb86791-0817-4a12-b94f-21b476c48b77.png)  
it looks like depth viewer is using my GPU.

### Actual Result

"ZED Explorer" works fine.

### ZED Camera model

ZED Mini

### Environment

```shell
OS: Windows
CPU: Intel
GPU: NVIDIA GEFORECE 940MX
ZED SDK VERSION: 3.8.2
```

**Comment by Myzhar** [comment]
Hi @junsukha 
the NVIDIA GEFORECE 940MX is a GPU based on Maxwell architecture and it does not support CUDA v11.x.
You must install CUDA 10.2 and the ZED SDK for this version.

This is a known issue, reported in the SDK download page:
![image](https://user-images.githubusercontent.com/3648617/220056982-2c7d5e56-7418-4fb1-8233-26a398a35a9d.png)
