### ISSUE TITLE
question on timestamps corresponding  the images

### ISSUE THREAD

**Issue by B-Betty** [stereolabs/zed-examples#55]
hi. how can I get the timestamps while I get the left and depth image Simultaneously???

**Comment by WASCHMASCHINE** [comment]
There is a retrieval time example in the ROS-Wrapper sample.
The "real" timestamps should be identical, since the depth image corresponds to that stereo pair at that timepoint.

**Comment by WASCHMASCHINE** [comment]
https://www.stereolabs.com/developers/documentation/API/v2.3.3/classsl_1_1Camera.html#a737689d57677bfdbb030b36c5498cdec

Just search the API, it is quite small.

**Comment by B-Betty** [comment]
thank you very much!
