### ISSUE TITLE
Intrinsics of depth map.

### ISSUE THREAD

**Issue by JackHunt** [stereolabs/zed-examples#62]
Hi,
Is there a way to extract the projection matrix C from the depth map produced by the ZED SDK? In the documentation I can only see this functionality for each of the RGB sensors. What if one wishes to perform projections using the depth map alone?

This would be useful to use the Zed as a drop in replacement for sensors such as the PrimeSense, where the projection matrix is required to raycast in to a volume such as a TSDF.

Best regards,
Jack

**Comment by WASCHMASCHINE** [comment]
@JackHunt: Yes, if you know the used calibration file (*.conf). Then you can backproject with cx,cy,fx,fy and the depth value. 

Also notice that a depth map has no intrinsics, but only the camera model has extrinsical and intrinsical parameters.

**Comment by JackHunt** [comment]
Ah yes, thank you. I wasn't sure if the depth map properties would be defined by the sensor intrinsics and thus require an additional projection matrix.
