### ISSUE TITLE
can not find function isValidMeasure()

### ISSUE THREAD

**Issue by Leonslam** [stereolabs/zed-examples#66]
I have two questions when using zed with sdk.

First, I can grab image_1 with the param "VIEW_LEFT" and image_2 with the param "VIEW_LEFT_UNRECTIFIED", which image's pixels is aligned with the depth image(data)?

Second, how can I judge  if the depth image's value is valid? According to the overview (https://docs.stereolabs.com/overview/depth-sensing/advanced-settings/) I can use isValidMeasure() but I can not find it in the header files.

**Comment by obraun-sl** [comment]
Hi,

* Image with VIEW_LEFT is the one aligned with the depth data/image. the unrectified is the raw image coming from the camera and therefore not rectified and undistorted.

* isValidMeasure() is located in sl_zed/defines.hpp. It basically calls std::isfinite() to check if the pixel is valid.

Best,

**Comment by Leonslam** [comment]
Many thanks!
