### ISSUE TITLE
ZED not detected by SDK but detected by lsusb

### ISSUE THREAD

**Issue by bridger217** [stereolabs/zed-examples#67]
Hello,

I'm running Ubuntu 16.04 (kernel v 4.13.0) and cannot get the ZED camera to be detected by the SDK software. Originally, I was running SDK v2.4 and cuda 9.1 on a nvidia 390.48 driver. The very first time I set up the camera, I ran the Explorer, updated the firmware, and briefly saw what the camera was seeing before it crashed. I tried running explorer afterwards and it crashed every time, saying "waiting for camera...". When I ran the diagnostic, it seg-faulted when it got to the part where it checked the camera.

Then I tried running it on cuda 8.0 and SDK v2.1 and when I run the diagnostic it says

"Running usb Diagnostic : Failed 
Error:
    ZED not detected, check your USB drivers and avoid hubs or cable extension.
"

The device is listed when I run the lsusb command (as Bus 002 Device 010: ID 2b03:f582)

**Comment by obraun-sl** [comment]
Hi,

2b03:f582 means that your camera is working correcly but with new firmware : new firmware has been completely refactored (for better windows compatibility) and therefore only compatible with SDK 2.4 and future version.

Best would be to see what's going on SDK2.4 . Did you try other tools and samples from 2.4? they all crash?

**Comment by bridger217** [comment]
Thanks for the quick response, but I ended up downgrading firmware to v1142 and running SDK v2.2.1 w/ cuda 9.0 and it's working now!
