### ISSUE TITLE
Documentation wrong

### ISSUE THREAD

**Issue by michela** [stereolabs/zed-examples#7]
Re commit 893688bcdf8f4ba4290bc7af08d3aa428086478d

 ./ZED_SVO_Recording -f="./mysvo.svo" -v="./mysvo_converted.avi"  -z

Doco says -v but exe output says use -o for output

Neither avi or sequence exporting working. Empty files generated

**Comment by nesnes** [comment]
Hi,
We changed the documentation to match the code, it's the -o --output option to specify the output directory.

An issue was indeed affecting the video/images exportation, we've just pushed the fix 3ef0e7d.

Thanks for pointing out this issue.
