### ISSUE TITLE
cMake finding cuda 7.5, but 9.0 is installed

### ISSUE THREAD

**Issue by bridger217** [stereolabs/zed-examples#70]
I'm running SDK 2.2.1 with cuda 9.0 on Ubuntu 16.04 (not up to date because the newer versions were not working with my kernel) and when I try to run the cmake in any of the sample directories, I get the error:

Could NOT find CUDA: Found unsuitable version "7.5", but required is exact
  version "9" (found /usr)

and the error log's output:

cat CMakeError.log 
Determining if the pthread_create exist failed with the following output:
Change Dir: /usr/local/zed/sample/spatial mapping/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_86332/fast"
/usr/bin/make -f CMakeFiles/cmTC_86332.dir/build.make CMakeFiles/cmTC_86332.dir/build
make[1]: Entering directory '/usr/local/zed/sample/spatial mapping/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_86332.dir/CheckSymbolExists.c.o
/usr/bin/cc    -fPIC    -o CMakeFiles/cmTC_86332.dir/CheckSymbolExists.c.o   -c "/usr/local/zed/sample/spatial mapping/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c"
Linking C executable cmTC_86332
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_86332.dir/link.txt --verbose=1
/usr/bin/cc  -fPIC     CMakeFiles/cmTC_86332.dir/CheckSymbolExists.c.o  -o cmTC_86332 -rdynamic 
CMakeFiles/cmTC_86332.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x1b): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_86332.dir/build.make:97: recipe for target 'cmTC_86332' failed
make[1]: *** [cmTC_86332] Error 1
make[1]: Leaving directory '/usr/local/zed/sample/spatial mapping/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_86332/fast' failed
make: *** [cmTC_86332/fast] Error 2

File /usr/local/zed/sample/spatial mapping/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /usr/local/zed/sample/spatial mapping/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_1b1ef/fast"
/usr/bin/make -f CMakeFiles/cmTC_1b1ef.dir/build.make CMakeFiles/cmTC_1b1ef.dir/build
make[1]: Entering directory '/usr/local/zed/sample/spatial mapping/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_1b1ef.dir/CheckFunctionExists.c.o
/usr/bin/cc    -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_1b1ef.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.5/Modules/CheckFunctionExists.c
Linking C executable cmTC_1b1ef
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_1b1ef.dir/link.txt --verbose=1
/usr/bin/cc  -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_1b1ef.dir/CheckFunctionExists.c.o  -o cmTC_1b1ef -rdynamic -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_1b1ef.dir/build.make:97: recipe for target 'cmTC_1b1ef' failed
make[1]: *** [cmTC_1b1ef] Error 1
make[1]: Leaving directory '/usr/local/zed/sample/spatial mapping/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_1b1ef/fast' failed
make: *** [cmTC_1b1ef/fast] Error 2

Cuda 9.0 is located in usr/local and is linked with the "cuda" alias. I've never downloaded cuda 7.5

**Comment by rnunziata** [comment]
I have the same issue:  in my case there are 7.5 cuda libs in /usr but my install  is in /usr/local ... I can not seem to override zed cmake in any way it will use the installed version. For some reason it keeps looking in  /usr even though I set all the environment vars and paths correctly.

**Comment by rnunziata** [comment]
Have a solution that worked for me. comment out in the CMakelist.txt file
```
#if(COMMAND cmake_policy)
#	cmake_policy(SET CMP0003 OLD)
#	cmake_policy(SET CMP0015 OLD)
#endif(COMMAND cmake_policy)
```
also make PATH env is set  in you bashrc file.
`export PATH=/usr/local/cuda/bin:$PATH`

**Comment by dogasiyli** [comment]
for anyone who still faces the issue and couldnt find a way..
changing 
*** find_package(CUDA) ***
line to
*** find_package(CUDA PATHS /usr/local/cuda-9.0) ***
in the ??.cmake file allows finding the right cuda

in the question posted above couldnt find such a line that shows any line that tells - cuda 7.5 is found by the cmake code..
but if it were there that line would have the one to be changed..

I came across this problem while trying to compile pytorch for an old graphics card.
