### ISSUE TITLE
Convert depth map to real world distance

### ISSUE THREAD

**Issue by sky-github** [stereolabs/zed-examples#72]
I have got the depth image form zed camera, but the value is 0-255. I wonder how can I convert the value to the real world distance.

**Comment by nesnes** [comment]
Hi

You probably used the `retreiveImage()` function which gives you a grayscale view of the depth. If you want the actual depth values, you should use `retreiveMeasure(myDepthMat, sl::MEASURE_DEPTH)`.

You can get the depth at a given pixel using: 
```
float z=0;
myDepthMat.getValue(pixelX, pixelY, &z);
```

Don't hesitate to take a look at the API documentation for more: https://www.stereolabs.com/developers/documentation/API/v2.4.0/
