### ISSUE TITLE
About save depth image 

### ISSUE THREAD

**Issue by liuhang0727** [stereolabs/zed-examples#77]
The depth image is captured with the format "sl::Mat sl::MAT_TYPE_32F_C1 ", while the "sl::Mat  read" and "sl::Mat  write" function can only read and write "MAT_TYPE_8U_C1, MAT_TYPE_8U_C3, MAT_TYPE_8U_C4". So I have the ｑｕestion than how can I save the depth data as a image? And how can I read again the saved depth image?

Thank you.

**Comment by WASCHMASCHINE** [comment]
Hi @liuhang0727,
I have a working solution for you:
1. Write an .EXR with 32FC1 cv::Mat (no flags, just name).
2. Read the .EXR with cv::IMREAD_UNCHANGED.

That's it.
