### ISSUE TITLE
Playback doesn't work on large file.

### ISSUE THREAD

**Issue by rpfly3** [stereolabs/zed-examples#83]
I try to playback a large file. But it cannot open it. It works on small files. Does any one have the problem?

**Comment by obraun-sl** [comment]
Hi,
What's the size of the SVO? What's the output : crash/error code ?
Best,
OB

**Comment by rpfly3** [comment]
@obraun-sl 
My SVO size is around 17 GB. There is no crash. The program only gets stuck there. 

I think the problem is that the SVO is on a flash. When I move it to local disk, it can work.
