### ISSUE TITLE
How to get images at 60 fps and imu data at 500hz at the same time? 

### ISSUE THREAD

**Issue by axing0805091** [stereolabs/zed-examples#89]
We know that imu sampling rate is much higher than image, so can I get images at 60 fps and imu data at 500hz at the same time? Is there an easy way? Or maybe I need to use two threads to achieve my goal ?

**Comment by nesnes** [comment]
Hi,

As you need to gather data at different frequency, you'll need two thread.
`grab()` and `getIMUData(myData, sl::TIME_REFERENCE_CURRENT)` are thread safe.
You can use `getTimestamp (sl::TIME_REFERENCE_IMAGE)` to get the last image timestamp, and `myData.timestamp` to get the IMU data one.
