### ISSUE TITLE
opencv and cuda

### ISSUE THREAD

**Issue by tomitrescak** [stereolabs/zed-examples#98]
Hi, would you have a recipe where I can directly upload frames to GPU from camera, without passing via cv::Mat? I would like to grab frame directly in GPU and process it there. Is that possible?

**Comment by Myzhar** [comment]
When you retrieve a Measure or an Image you can get the data directly in GPU memory using "MEM_GPU" for the "type" parameter:

https://www.stereolabs.com/developers/documentation/API/v2.3.0/classsl_1_1Camera.html#ac40f337ccc76cacd3412b93f7f4638e2

https://www.stereolabs.com/developers/documentation/API/v2.3.0/classsl_1_1Camera.html#af799d12342a7b884242fffdef5588a7f

https://www.stereolabs.com/developers/documentation/API/v2.3.0/group__Core__group.html#ga3fc8f9f9f84fbb0f728fc2cd399ade29

**Comment by tomitrescak** [comment]
@Myzhar thanks for the links. I tried that previously but I cannot make it work. Please consider following example, I always receive Unhandled exception.

```c
sl::Mat *frame_left_zed_gpu = new sl::Mat(new_width, new_height, MAT_TYPE_8U_C4);
cv::cuda:GpuMat frame_left_cuda = slMat2cvCudaMat(*frame_left_zed_gpu);

zed.retrieveImage(*frame_left_zed_gpu, VIEW_LEFT, MEM_GPU, new_width, new_height);

cv::cuda::GpuMat mask;
// don't mind the logic below, it's just for test
cv::cuda::absdiff(frame_left_cuda, frame_left_cuda, mask); // Exception


/**
* Conversion function between sl::Mat and cv::Mat
**/
cv::cuda::GpuMat slMat2cvCudaMat(Mat& input) {
	// Mapping between MAT_TYPE and CV_TYPE
	int cv_type = -1;
	switch (input.getDataType()) {
	case MAT_TYPE_32F_C1: cv_type = CV_32FC1; break;
	case MAT_TYPE_32F_C2: cv_type = CV_32FC2; break;
	case MAT_TYPE_32F_C3: cv_type = CV_32FC3; break;
	case MAT_TYPE_32F_C4: cv_type = CV_32FC4; break;
	case MAT_TYPE_8U_C1: cv_type = CV_8UC1; break;
	case MAT_TYPE_8U_C2: cv_type = CV_8UC2; break;
	case MAT_TYPE_8U_C3: cv_type = CV_8UC3; break;
	case MAT_TYPE_8U_C4: cv_type = CV_8UC4; break;
	default: break;
	}

	return cv::cuda::GpuMat(input.getHeight(), input.getWidth(), cv_type, input.getPtr<sl::uchar1>(MEM_GPU));
}
```

**Comment by Myzhar** [comment]
Can you give me more information about the kind of "Exception" you are getting?

**Comment by tomitrescak** [comment]
@Myzhar just a generic "Unhandled exception" and memory address in C++.

**Comment by Myzhar** [comment]
This code does not convince me:
```sl::Mat *frame_left_zed_gpu = new sl::Mat(new_width, new_height, MAT_TYPE_8U_C4);
cv::cuda:GpuMat frame_left_cuda = slMat2cvCudaMat(*frame_left_zed_gpu);```

Try instead:
```
sl::Mat frame_left_zed_gpu;
zed.retrieveImage(frame_left_zed_gpu, VIEW_LEFT, MEM_GPU, new_width, new_height);
cv::cuda:GpuMat frame_left_cuda = slMat2cvCudaMat(frame_left_zed_gpu);

cv::cuda::GpuMat mask;
// don't mind the logic below, it's just for test
cv::cuda::absdiff(frame_left_cuda, frame_left_cuda, mask);
```
